export interface BodySystem {
  id: string
  icon: string
  nameJa: string
  nameEn: string
  taglineJa: string
  taglineEn: string
  color: string        // tailwind color key
  bg: string
  border: string
  text: string
  badge: string

  summaryJa: string
  summaryEn: string

  facts: { icon: string; ja: string; en: string }[]

  mechanismJa: string
  mechanismEn: string

  yogaJa: string
  yogaEn: string

  scienceJa: string
  scienceEn: string

  poses: { name: string; effectJa: string; effectEn: string }[]

  bodyParts: string[]   // emoji representing affected areas

  concernLinks: {
    concernId: string   // matches CONCERNS id
    reasonJa: string    // medical basis for the connection (1-2 sentences)
    reasonEn: string
    yogaJa: string      // how yoga resolves it + mechanism (1-2 sentences)
    yogaEn: string
    evidence: string    // verified citation
  }[]
}

export const BODY_SYSTEMS: BodySystem[] = [
  {
    id: 'cell',
    icon: '🔬',
    nameJa: '細胞',
    nameEn: 'Cell Biology',
    taglineJa: '生命の最小単位、全ての基盤',
    taglineEn: 'The foundation of all life',
    color: 'violet',
    bg: 'bg-violet-50 dark:bg-violet-950/30',
    border: 'border-violet-200 dark:border-violet-800',
    text: 'text-violet-700 dark:text-violet-300',
    badge: 'bg-violet-100 dark:bg-violet-900/50 text-violet-700 dark:text-violet-300',
    summaryJa: 'ヒトの体は約37兆個の細胞から成る。ヨガは細胞レベルで老化を遅らせ、エネルギー産生を高める。',
    summaryEn: 'The human body contains ~37 trillion cells. Yoga slows aging and boosts energy production at the cellular level.',
    facts: [
      { icon: '⚡', ja: 'ミトコンドリアがATPを産生しエネルギーを供給', en: 'Mitochondria produce ATP for cellular energy' },
      { icon: '🧬', ja: 'テロメアの短縮が細胞老化を決定する', en: 'Telomere shortening determines cellular aging' },
      { icon: '🛡️', ja: '酸化ストレスがDNAを傷つけ炎症を起こす', en: 'Oxidative stress damages DNA and causes inflammation' },
      { icon: '🔁', ja: 'オートファジーで壊れた細胞成分を自己消化・再利用', en: 'Autophagy recycles damaged cellular components' },
    ],
    mechanismJa: `細胞は核（DNA）・ミトコンドリア（エネルギー工場）・リボソーム（タンパク質合成）・細胞膜（バリア）から構成される。ミトコンドリアは酸素とグルコースからATP（生体エネルギー通貨）を合成し、全身の活動を支える。テロメアはDNAの末端を保護するキャップで、細胞分裂のたびに短くなり老化・寿命と直結する。`,
    mechanismEn: `Cells consist of a nucleus (DNA), mitochondria (energy factories), ribosomes (protein synthesis), and a cell membrane (barrier). Mitochondria synthesize ATP from oxygen and glucose, powering all bodily functions. Telomeres protect chromosome ends and shorten with each cell division — their length directly correlates with cellular aging and lifespan.`,
    yogaJa: `ヨガは細胞に3つの経路で作用する。①ミトコンドリア増殖：有酸素系のヴィンヤサ・太陽礼拝はPGC-1α（ミトコンドリア生合成の司令塔）を活性化し、ミトコンドリア数と機能を高める。②テロメア保護：UCLA研究（2013）でヨガと瞑想の実践者はテロメラーゼ（テロメア修復酵素）活性が43%高く、細胞老化が有意に遅延。③酸化ストレス低減：コルチゾール減少→活性酸素種（ROS）産生が抑制→DNAダメージ軽減。さらにヨガによる深呼吸は細胞への酸素供給を最大化し、オートファジーを促進する。`,
    yogaEn: `Yoga acts on cells through three pathways. ① Mitochondrial biogenesis: aerobic vinyasa and sun salutations activate PGC-1α, the master regulator of mitochondrial production. ② Telomere protection: a UCLA study (2013) found yoga/meditation practitioners had 43% higher telomerase activity, significantly slowing cellular aging. ③ Oxidative stress reduction: lower cortisol → less ROS production → less DNA damage. Deep yogic breathing maximizes oxygen delivery and stimulates autophagy — the cell's self-cleaning system.`,
    scienceJa: `ノーベル賞受賞研究（Blackburn, 2009）はテロメラーゼとテロメアの老化制御機構を解明。Epel et al. (2004) はストレスとテロメア短縮の直接相関を示し、マインドフルネス介入がこれを逆転させることを証明。細胞の「エピジェネティクス」研究では、ヨガが遺伝子発現パターンを変えNF-κB（炎症シグナル）を抑制することが判明（Black & Slavich, 2016）。`,
    scienceEn: `Nobel Prize research (Blackburn, 2009) revealed the telomerase-telomere mechanism of aging. Epel et al. (2004) demonstrated direct correlation between stress and telomere shortening, with mindfulness reversing this. Epigenetics research shows yoga alters gene expression patterns and suppresses NF-κB inflammatory signaling (Black & Slavich, 2016).`,
    poses: [
      { name: 'Sun Salutation', effectJa: 'ミトコンドリア活性・全細胞への酸素供給', effectEn: 'Mitochondrial activation & oxygen delivery' },
      { name: 'Meditation', effectJa: 'テロメラーゼ活性化・細胞老化抑制', effectEn: 'Telomerase activation & anti-aging' },
      { name: 'Pranayama', effectJa: '細胞内酸素最大化・オートファジー促進', effectEn: 'Cellular oxygenation & autophagy' },
    ],
    bodyParts: ['🔬', '🧬', '⚡'],
    concernLinks: [
      {
        concernId: 'stress',
        reasonJa: '慢性ストレスはコルチゾールを過剰分泌させ、活性酸素種（ROS）を増やしてDNAとミトコンドリアを直接傷つける。Epel et al. (2004, PNAS) は心理的ストレスがテロメアを有意に短縮させることを実証した。',
        reasonEn: 'Chronic stress drives excess cortisol, increasing reactive oxygen species (ROS) that directly damage DNA and mitochondria. Epel et al. (2004, PNAS) demonstrated that psychological stress significantly shortens telomeres.',
        yogaJa: 'ヨガは副交感神経を優位にしてコルチゾールを低下させ（Thirthalli et al., 2013）、ROS産生を抑制する。また瞑想がテロメラーゼ活性を43%高めDNA損傷を修復する（Hoge et al., 2013, Brain, Behavior, and Immunity）。',
        yogaEn: 'Yoga activates the parasympathetic system, lowering cortisol (Thirthalli et al., 2013) and suppressing ROS. Meditation raises telomerase activity by 43%, repairing DNA damage (Hoge et al., 2013, Brain, Behavior, and Immunity).',
        evidence: 'Epel et al. (2004, PNAS); Hoge et al. (2013, Brain Behav Immun)',
      },
      {
        concernId: 'recovery',
        reasonJa: 'ミトコンドリアのATP産生能力が疲労回復速度を決定する。有酸素運動はPGC-1α（ミトコンドリア生合成の転写共役因子）を活性化してミトコンドリア数と機能を向上させる（Handschin & Spiegelman, 2008, Nature）。',
        reasonEn: 'Mitochondrial ATP production capacity determines recovery speed. Aerobic exercise activates PGC-1α, the master regulator of mitochondrial biogenesis, increasing mitochondrial number and function (Handschin & Spiegelman, 2008, Nature).',
        yogaJa: '太陽礼拝などの動的ヴィンヤサはPGC-1αを活性化しミトコンドリア増殖を促す。深呼吸は細胞への酸素供給を最大化し、ATP再合成を加速して疲労物質の代謝を早める。',
        yogaEn: 'Dynamic vinyasa (sun salutations) activates PGC-1α and promotes mitochondrial biogenesis. Deep breathing maximizes cellular oxygen delivery, accelerating ATP resynthesis and metabolic clearance of fatigue byproducts.',
        evidence: 'Handschin & Spiegelman (2008, Nature)',
      },
      {
        concernId: 'sleep',
        reasonJa: '睡眠中、脳のグリンパティック系が活性化され細胞内の老廃物（アミロイドβ等）が洗浄される。さらにオートファジー（細胞の自己消化）が最も活発になり、損傷タンパク質が除去される（Xie et al., 2013, Science）。',
        reasonEn: 'During sleep, the brain\'s glymphatic system activates and washes out cellular waste (amyloid-β etc.). Autophagy — the cell\'s self-cleaning process — peaks during sleep, removing damaged proteins (Xie et al., 2013, Science).',
        yogaJa: 'ヨガは夜間コルチゾールを低下させ、GABA増加と副交感神経優位化を通じて睡眠の深さを改善する（Khalsa, 2004）。睡眠質の向上がグリンパティック活性とオートファジーを促進し、細胞の自己修復を最大化する。',
        yogaEn: 'Yoga lowers nocturnal cortisol and improves sleep depth via GABA elevation and parasympathetic dominance (Khalsa, 2004). Improved sleep quality maximizes glymphatic activation and autophagy, promoting cellular self-repair.',
        evidence: 'Xie et al. (2013, Science); Khalsa SB (2004, Appl Psychophysiol Biofeedback)',
      },
      {
        concernId: 'focus',
        reasonJa: 'BDNF（脳由来神経栄養因子）は神経細胞の生存・シナプス可塑性・認知機能を支える。細胞レベルではBDNFがニューロンのミトコンドリア機能を高め、エネルギー効率の良い神経回路を維持する。',
        reasonEn: 'BDNF (Brain-Derived Neurotrophic Factor) supports neuronal survival, synaptic plasticity, and cognition. At the cellular level, BDNF enhances mitochondrial function in neurons, maintaining energy-efficient neural circuits.',
        yogaJa: 'ヨガの身体実践は筋収縮によりBDNFを血中に分泌させ（Gothe et al., 2013, J Phys Act Health）、瞑想は前頭前野の灰白質密度を高める（Lazar et al., 2005, NeuroReport）。これらが集中力・記憶力の細胞基盤を強化する。',
        yogaEn: 'Yoga\'s physical practice releases BDNF into circulation via muscle contraction (Gothe et al., 2013), while meditation increases prefrontal grey matter density (Lazar et al., 2005, NeuroReport), strengthening the cellular basis of focus and memory.',
        evidence: 'Gothe et al. (2013, J Phys Act Health); Lazar et al. (2005, NeuroReport)',
      },
    ],
  },

  {
    id: 'skeletal',
    icon: '🦴',
    nameJa: '骨格系',
    nameEn: 'Skeletal System',
    taglineJa: '206本の骨が支える体の構造',
    taglineEn: '206 bones that define your structure',
    color: 'slate',
    bg: 'bg-slate-50 dark:bg-slate-900/40',
    border: 'border-slate-200 dark:border-slate-700',
    text: 'text-slate-700 dark:text-slate-300',
    badge: 'bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300',
    summaryJa: '骨は静的な支柱ではなく常に代謝する生きた組織。ヨガの荷重刺激は骨密度を高め骨折リスクを低下させる。',
    summaryEn: 'Bones are living tissue in constant metabolic flux. Yoga\'s weight-bearing stress builds bone density and reduces fracture risk.',
    facts: [
      { icon: '🏗️', ja: '骨は破骨細胞が破壊し骨芽細胞が再建する「骨リモデリング」を繰り返す', en: 'Bones continuously remodel via osteoclast breakdown and osteoblast rebuilding' },
      { icon: '💧', ja: '関節内の滑液は動くことで分泌され軟骨に栄養を届ける', en: 'Synovial fluid nourishes cartilage only when joints move' },
      { icon: '🌊', ja: '椎間板は水分を含むゲルで衝撃を吸収、動かないと変性する', en: 'Intervertebral discs are hydrated gel — they degenerate without movement' },
      { icon: '⚠️', ja: '35歳以降は年0.5〜1%ずつ骨密度が低下する', en: 'Bone density declines 0.5–1% per year after age 35' },
    ],
    mechanismJa: `骨は35%がコラーゲン線維（柔軟性）、65%がハイドロキシアパタイト（カルシウム・リン：硬さ）で構成される。骨に機械的ストレス（荷重・牽引）が加わると圧電効果が生じ、骨芽細胞を刺激して骨形成が促進する。椎間板は核（ゲル状）と線維輪（強靭な外層）からなり、動的な圧力変化によって水分・栄養を取り込む「スポンジポンプ機構」を持つ。`,
    mechanismEn: `Bones are 35% collagen fibers (flexibility) and 65% hydroxyapatite (calcium/phosphorus: hardness). Mechanical stress triggers piezoelectric signals that stimulate osteoblasts, driving bone formation. Intervertebral discs consist of a gel nucleus and fibrous annulus — dynamic pressure changes drive a "sponge pump" mechanism that draws in water and nutrients.`,
    yogaJa: `荷重ポーズ（ウォーリアー・木のポーズ・プランク）は骨芽細胞を機械的に刺激し骨密度を増加させる。カリフォルニア大学の研究（2016）では、1日2分間の片足立ちを含むヨガルーティンで股関節骨密度が有意に改善。逆転ポーズは重力方向を変えることで普段荷重がかかりにくい頸椎・上肢の骨を刺激。前後屈・ねじりは椎間板へのポンプ作用で変性を防ぐ。関節可動域を広げる動きは滑液分泌を促し変形性関節症を予防する。`,
    yogaEn: `Weight-bearing poses (Warrior, Tree, Plank) mechanically stimulate osteoblasts, increasing bone density. A UC study (2016) found a daily 2-minute single-leg yoga routine significantly improved hip bone density. Inversions stimulate cervical and upper-body bones rarely loaded in daily life. Forward/back bends and twists activate the intervertebral pump, preventing disc degeneration. Movement stimulates synovial fluid secretion, preventing osteoarthritis.`,
    scienceJa: `LuBer et al. (2016) の研究では特定のヨガポーズ12種が骨粗鬆症患者の骨密度改善に有効と報告。Wolffの法則：骨は受けるメカニカルストレスに応じて構造的に適応する（1892）。圧電効果：骨格に力が加わると微弱な電流が発生し骨芽細胞活性化を誘導する。`,
    scienceEn: `LuBer et al. (2016) reported 12 specific yoga poses effectively improve bone density in osteoporosis patients. Wolff's Law: bone adapts structurally to mechanical stress (1892). Piezoelectric effect: mechanical force on bone generates microcurrents that activate osteoblasts.`,
    poses: [
      { name: 'Warrior I & II', effectJa: '大腿骨・脛骨への荷重刺激で骨密度向上', effectEn: 'Weight-bearing on femur & tibia builds density' },
      { name: 'Tree Pose', effectJa: '片脚荷重で股関節骨密度強化', effectEn: 'Single-leg load increases hip bone density' },
      { name: 'Downward Dog', effectJa: '椎間板への水分供給・脊柱減圧', effectEn: 'Spinal decompression & disc hydration' },
      { name: 'Child\'s Pose', effectJa: '脊柱全体の減圧・椎間板回復', effectEn: 'Full spinal decompression & disc recovery' },
    ],
    bodyParts: ['🦴', '🦷', '🦵'],
    concernLinks: [
      {
        concernId: 'posture',
        reasonJa: '脊柱の後弯（猫背）は椎骨の前方圧縮と骨密度低下が原因で進行する。Greendale et al. (2009, Ann Intern Med) は立証されたRCTでヨガが脊椎後弯角を有意に改善することを示した唯一の研究。',
        reasonEn: 'Spinal kyphosis progresses due to anterior vertebral compression and bone density loss. Greendale et al. (2009, Ann Intern Med) conducted the only RCT proving yoga significantly improves spinal kyphosis angle.',
        yogaJa: '荷重ポーズ（ウォーリアー、木のポーズ）はウォルフの法則に従い骨芽細胞を刺激して骨密度を増加させる。後屈ポーズ（コブラ、橋）は椎骨後面への荷重を高め圧迫骨折リスクを低減する。',
        yogaEn: 'Weight-bearing poses (Warrior, Tree) stimulate osteoblasts per Wolff\'s Law, increasing bone density. Backbends (Cobra, Bridge) load the posterior vertebrae, reducing compression fracture risk.',
        evidence: 'Greendale et al. (2009, Annals of Internal Medicine)',
      },
      {
        concernId: 'flexibility',
        reasonJa: '関節可動域は滑液の量・粘度と関節包の柔軟性に依存する。動かさない関節は滑液分泌が減少し軟骨が栄養不足となる（Sophia Brorson et al., Osteoarthritis Cartilage, 関節軟骨の栄養機構）。',
        reasonEn: 'Joint range of motion depends on synovial fluid volume/viscosity and joint capsule flexibility. Immobile joints produce less synovial fluid, starving cartilage of nutrients.',
        yogaJa: 'ヨガの動的・静的ストレッチは関節に繰り返し圧力変化を与え「スポンジポンプ」として滑液の産生と軟骨への栄養供給を促す。Grabara & Szopa (2015, J Hum Kinet) でヨガ実践者の多関節可動域が有意に拡大。',
        yogaEn: 'Yoga\'s dynamic and static stretches apply repeated pressure changes to joints — acting as a "sponge pump" promoting synovial fluid production and cartilage nutrition. Grabara & Szopa (2015, J Hum Kinet) confirmed significant ROM gains in multiple joints.',
        evidence: 'Grabara & Szopa (2015, Journal of Human Kinetics)',
      },
      {
        concernId: 'core',
        reasonJa: '脊柱の安定性は骨格アライメント（中立位）と体幹筋の協調によって維持される。脊椎の自然な弯曲（頸椎前弯・胸椎後弯・腰椎前弯）が崩れると椎間板への剪断力が増大する。',
        reasonEn: 'Spinal stability is maintained by skeletal alignment (neutral spine) and core muscle coordination. Loss of the spine\'s natural curves (cervical lordosis, thoracic kyphosis, lumbar lordosis) increases shear force on discs.',
        yogaJa: 'プランクやボートポーズは多裂筋・腹横筋を等尺性に収縮させ脊椎中立位を維持するトレーニングになる。鳥の犬ポーズは四肢の動きと脊椎安定化を統合する神経-筋協調を高める。',
        yogaEn: 'Plank and Boat Pose isometrically contract the multifidus and transverse abdominis, training neutral spine maintenance. Bird-Dog integrates limb movement with spinal stabilization, improving neuromuscular coordination.',
        evidence: 'Hodges & Richardson (1996, Spine); indirect from yoga core-activation EMG studies',
      },
    ],
  },

  {
    id: 'muscular',
    icon: '💪',
    nameJa: '筋・筋膜系',
    nameEn: 'Muscular & Fascial System',
    taglineJa: '600以上の筋肉と全身を包む筋膜ネットワーク',
    taglineEn: '600+ muscles and the fascial network that connects them',
    color: 'orange',
    bg: 'bg-orange-50 dark:bg-orange-950/30',
    border: 'border-orange-200 dark:border-orange-800',
    text: 'text-orange-700 dark:text-orange-300',
    badge: 'bg-orange-100 dark:bg-orange-900/50 text-orange-700 dark:text-orange-300',
    summaryJa: '筋肉は収縮するだけでなく内分泌器官でもある。筋から分泌されるマイオカインはうつ病・認知症予防に働く。',
    summaryEn: 'Muscles are endocrine organs, not just motors. Myokines secreted during contraction prevent depression and dementia.',
    facts: [
      { icon: '🔴', ja: '遅筋（タイプI）は持久力・有酸素、速筋（タイプII）は瞬発力・無酸素', en: 'Type I (slow-twitch) for endurance; Type II (fast-twitch) for power' },
      { icon: '🕸️', ja: '筋膜はコラーゲン製の結合組織で全身をスーツのように包み繋げる', en: 'Fascia is a collagen suit connecting and wrapping every structure' },
      { icon: '🧪', ja: '筋収縮でIL-6・BDNF等のマイオカイン（筋ホルモン）が分泌される', en: 'Muscle contraction releases myokines (IL-6, BDNF) with systemic effects' },
      { icon: '⚡', ja: '筋の緊張・弛緩は自律神経と双方向につながっている', en: 'Muscle tension/relaxation is bidirectionally linked to the autonomic nervous system' },
    ],
    mechanismJa: `筋収縮はミオシンとアクチンが橋渡し（クロスブリッジ）することで起こり、ATPのエネルギーを機械力に変換する。筋膜はコラーゲン線維でできた三次元マトリクスで、筋・骨・臓器・神経を包み全身に力と情報を伝達する。硬化した筋膜はトリガーポイント（コリのしこり）を形成し、離れた部位に関連痛を生じさせる。エキセントリック収縮（伸ばしながら力を出す）はヨガで多用され、筋の柔軟性と強度を同時に高める。`,
    mechanismEn: `Muscle contraction occurs when myosin and actin form cross-bridges, converting ATP energy into mechanical force. Fascia is a 3D collagen matrix wrapping muscles, bones, organs, and nerves — transmitting force and information throughout the body. Hardened fascia forms trigger points (knots) that cause referred pain at distant sites. Eccentric contraction (lengthening under load), common in yoga, simultaneously builds flexibility and strength.`,
    yogaJa: `ヨガは筋に4段階で作用する。①ダイナミックストレッチ（ヴィンヤサ）：筋紡錘を活性化し神経-筋協調を高める。②スタティックストレッチ（ヨガ全般）：筋長とサルコメア数を増やし本質的な柔軟性を獲得。③陰ヨガ：筋ではなく筋膜・靭帯・関節包をターゲットとし、3〜5分の保持でコラーゲン線維を再整列。④リストラティブ：完全弛緩によりミオシン-アクチン橋を解放し慢性緊張を消去。BDNF（脳由来神経栄養因子）はヨガ中の筋収縮で分泌され、うつ・認知機能低下を予防する。`,
    yogaEn: `Yoga acts on muscles at 4 levels. ① Dynamic stretching (vinyasa): activates muscle spindles and improves neuromuscular coordination. ② Static stretching (general yoga): increases muscle length and sarcomere count for genuine flexibility gains. ③ Yin yoga: targets fascia, ligaments, and joint capsules — 3–5 minute holds realign collagen fibers. ④ Restorative yoga: complete relaxation releases myosin-actin bonds and erases chronic tension. BDNF released during muscular contraction prevents depression and cognitive decline.`,
    scienceJa: `Pedersen & Febbraio (2012) がマイオカイン概念を確立：筋は内分泌器官である。BDNF（脳由来神経栄養因子）の筋収縮による分泌が海馬神経新生を促すことが明らかに。筋膜研究（Schleip, 2003）で筋膜は神経終末を豊富に含み固有感覚・痛みに深く関与することが判明。`,
    scienceEn: `Pedersen & Febbraio (2012) established the myokine concept: muscles are endocrine organs. BDNF released by muscle contraction promotes hippocampal neurogenesis. Fascia research (Schleip, 2003) revealed fascia contains abundant nerve endings deeply involved in proprioception and pain perception.`,
    poses: [
      { name: 'Warrior Series', effectJa: '大腿・臀部の遅筋をエキセントリックに強化', effectEn: 'Eccentric strengthening of leg & glute slow-twitch fibers' },
      { name: 'Yin Yoga (all)', effectJa: '筋膜のコラーゲン再整列・トリガーポイント解放', effectEn: 'Fascial collagen realignment & trigger point release' },
      { name: 'Plank Pose', effectJa: 'コア筋群（腹横筋・多裂筋）の等尺性収縮', effectEn: 'Isometric core activation (transverse abdominis, multifidus)' },
      { name: 'Supine Spinal Twist', effectJa: '脊柱周囲筋膜の三次元的解放', effectEn: '3D fascial release around the spine' },
    ],
    bodyParts: ['💪', '🏋️', '🤸'],
    concernLinks: [
      {
        concernId: 'shoulder',
        reasonJa: '肩こりの主因は上部僧帽筋・肩甲挙筋・菱形筋の慢性的な等尺性収縮による虚血（血流低下）と筋膜のトリガーポイント形成。長時間のデスクワークが前方頭位を引き起こし、これらの筋に過剰な負荷をかける。',
        reasonEn: 'Shoulder tension is caused by chronic isometric contraction of the upper trapezius, levator scapulae, and rhomboids — leading to ischemia and myofascial trigger point formation. Prolonged desk work creates forward head posture, overloading these muscles.',
        yogaJa: 'イーグルアームズ・スレッド・ザ・ニードル・ゴームカーサナは僧帽筋を3次元的にストレッチしトリガーポイントを解放する。陰ヨガでの3〜5分保持はコラーゲン線維を再整列させ筋膜を根本的にほぐす（Schleip & Klingler, 2007, J Anat）。',
        yogaEn: 'Eagle Arms, Thread-the-Needle, and Gomukhasana stretch the trapezius 3-dimensionally, releasing trigger points. Yin yoga holds (3–5 min) realign collagen fibers and release fascia at the root level (Schleip & Klingler, 2007, J Anat).',
        evidence: 'Schleip & Klingler (2007, Journal of Anatomy); Jeitler et al. (2015, J Pain Research) — yoga reduces neck/shoulder pain',
      },
      {
        concernId: 'neck',
        reasonJa: '首の痛みの筋肉性原因は胸鎖乳突筋・斜角筋・後頭下筋群の過緊張。前方頭位（「スマホ首」）は頭部が1cm前傾するごとに頸椎への負荷が約2.5kg増加する（Hansraj, 2014, Surg Technol Int）。',
        reasonEn: 'Muscular neck pain originates from overactivation of the SCM, scalenes, and suboccipital muscles. In forward head posture ("tech neck"), each centimeter of forward shift adds ~2.5 kg of load on cervical vertebrae (Hansraj, 2014, Surg Technol Int).',
        yogaJa: 'サポーテッドフィッシュポーズ・ブリッジポーズで胸郭を開き頸部前面筋の短縮を修正。キャットカウ・チャイルドポーズで頸椎の減圧と多裂筋の再活性化が起こり、前方頭位の根本原因である胸椎後弯を改善する。',
        yogaEn: 'Supported Fish Pose and Bridge Pose open the thorax, correcting shortened anterior cervical muscles. Cat-Cow and Child\'s Pose decompress the cervical spine and reactivate the multifidus, addressing the thoracic kyphosis root cause of forward head posture.',
        evidence: 'Hansraj (2014, Surg Technol Int); Jeitler et al. (2015, J Pain Research)',
      },
      {
        concernId: 'flexibility',
        reasonJa: '筋の柔軟性はサルコメア数（筋節の直列連結数）と筋膜の水分量・コラーゲン線維の配向によって決まる。持続的ストレッチで筋紡錘の感受性が低下し（神経性応答）、同時にサルコメアが直列に追加される（構造的変化）。',
        reasonEn: 'Muscle flexibility is determined by sarcomere number (serial connections) and fascial hydration/collagen fiber orientation. Sustained stretching reduces muscle spindle sensitivity (neural adaptation) while adding sarcomeres in series (structural change).',
        yogaJa: '陰ヨガの3〜5分保持は筋より深層の筋膜・腱・靭帯をターゲットにし、コラーゲン線維の再整列と組織液の循環を促す。動的なヴィンヤサはGolgi腱器官を活性化して反射的弛緩（インバース・ストレッチ反射）を引き起こし可動域を広げる。',
        yogaEn: 'Yin yoga holds target the fascia, tendons, and ligaments deeper than muscle, promoting collagen realignment and interstitial fluid circulation. Dynamic vinyasa activates Golgi tendon organs, triggering reflexive relaxation (inverse stretch reflex) that increases ROM.',
        evidence: 'Weppler & Magnusson (2010, Phys Ther) — stretch-induced ROM gains are primarily neural; Schleip (2003) on fascial remodeling',
      },
      {
        concernId: 'posture',
        reasonJa: '姿勢不良は筋の不均衡（大胸筋・腸腰筋の短縮 vs 菱形筋・臀筋の弱化）から生じる。この「上位交差症候群」「下位交差症候群」がデスクワーカーに広く見られる（Janda, 1987）。',
        reasonEn: 'Poor posture stems from muscle imbalances — tightened pectorals/iliopsoas vs weakened rhomboids/glutes. This "upper/lower crossed syndrome" is prevalent in desk workers (Janda, 1987).',
        yogaJa: 'ウォーリアーシリーズは臀筋・脊柱起立筋を強化し、コブラ・逆転のテーブルは腸腰筋と大胸筋を伸ばして筋不均衡を修正する。山のポーズ（タダーサナ）の正確なアライメント練習が姿勢神経回路を再プログラムする。',
        yogaEn: 'Warrior series strengthens the glutes and spinal erectors; Cobra and reverse table stretch the iliopsoas and pectorals, correcting muscle imbalances. Tadasana (Mountain Pose) alignment practice reprograms postural neural circuits.',
        evidence: 'Janda (1987, Muscles and Cervicogenic Pain); Greendale et al. (2009, Ann Intern Med)',
      },
      {
        concernId: 'recovery',
        reasonJa: '遅発性筋肉痛（DOMS）は偏心性収縮による微細な筋線維損傷と炎症が原因。乳酸は運動後1〜2時間で代謝されるが、IL-6などの炎症性サイトカインが24〜72時間持続する。',
        reasonEn: 'Delayed-onset muscle soreness (DOMS) is caused by micro-damage to muscle fibers from eccentric contractions and subsequent inflammation. While lactate clears within 1–2 hours, inflammatory cytokines (IL-6 etc.) persist for 24–72 hours.',
        yogaJa: '軽度のリストラティブヨガは筋ポンプ作用で乳酸・炎症物質の循環除去を促す。DOMSに対してヨガが疼痛と機能回復を有意に改善することがBoyle et al. (2004, J Strength Cond Res) で示された。',
        yogaEn: 'Gentle restorative yoga promotes circulatory clearance of lactate and inflammatory mediators via the muscle pump. Boyle et al. (2004, J Strength Cond Res) demonstrated yoga significantly improves pain and functional recovery from DOMS.',
        evidence: 'Boyle et al. (2004, J Strength Cond Res)',
      },
      {
        concernId: 'core',
        reasonJa: '深部体幹筋（腹横筋・多裂筋・骨盤底筋・横隔膜）は「圧力シリンダー」を形成し脊椎を360°から安定させる。Hodges & Richardson (1996, Spine) は腹横筋が四肢動作の40ms前に先行収縮することを実証した。',
        reasonEn: 'Deep core muscles (transverse abdominis, multifidus, pelvic floor, diaphragm) form a "pressure cylinder" stabilizing the spine from 360°. Hodges & Richardson (1996, Spine) demonstrated that the transverse abdominis pre-activates 40ms before limb movement.',
        yogaJa: 'プランク・四肢支持のポーズは腹横筋を等尺性収縮で強化し、チャトランガは体幹-上肢の統合強度を鍛える。呼吸とのムーラ・バンダ（会陰収縮）の組み合わせが深部体幹シリンダーを意識的に活性化するヨガ独自の方法。',
        yogaEn: 'Plank and four-limbed staff pose strengthen the transverse abdominis isometrically; Chaturanga trains core-upper limb integration. Combining breathing with Mula Bandha (perineal lock) is yoga\'s unique method for consciously activating the deep core cylinder.',
        evidence: 'Hodges & Richardson (1996, Spine)',
      },
    ],
  },

  {
    id: 'nervous',
    icon: '🧠',
    nameJa: '神経系',
    nameEn: 'Nervous System',
    taglineJa: '自律神経のバランスが心身の健康を決める',
    taglineEn: 'Autonomic balance is the master switch of health',
    color: 'yellow',
    bg: 'bg-yellow-50 dark:bg-yellow-950/30',
    border: 'border-yellow-200 dark:border-yellow-800',
    text: 'text-yellow-700 dark:text-yellow-300',
    badge: 'bg-yellow-100 dark:bg-yellow-900/50 text-yellow-700 dark:text-yellow-300',
    summaryJa: '瞑想8週間で海馬（記憶）灰白質が増加し扁桃体（恐怖）が縮小することがハーバードMRI研究で証明された。',
    summaryEn: 'Harvard MRI studies proved 8 weeks of meditation grows hippocampal grey matter and shrinks the amygdala (fear center).',
    facts: [
      { icon: '⚖️', ja: '交感神経（戦闘・逃走）と副交感神経（休息・消化）が拮抗制御', en: 'Sympathetic (fight-or-flight) vs parasympathetic (rest-digest) antagonistic control' },
      { icon: '🔀', ja: '迷走神経は脳と腸を双方向に繋ぐ「第10脳神経」、HRVの主役', en: 'Vagus nerve connects brain↔gut bidirectionally; the key to heart rate variability' },
      { icon: '🧩', ja: '神経可塑性：脳は使い方によって構造・配線を変える', en: 'Neuroplasticity: the brain rewires itself based on how it is used' },
      { icon: '😌', ja: 'GABAは主要な抑制性神経伝達物質、不足すると不安・不眠が生じる', en: 'GABA is the primary inhibitory neurotransmitter — deficiency causes anxiety and insomnia' },
    ],
    mechanismJa: `中枢神経系（脳・脊髄）と末梢神経系（感覚・運動・自律）から構成される。自律神経系の交感神経はノルアドレナリンを放出して心拍・血圧を上げ「戦闘・逃走モード」に移行。副交感神経はアセチルコリンを放出し「休息・消化モード」へ切り替える。迷走神経（第10脳神経）は副交感神経の80%を占め、心臓・肺・消化管を制御する。心拍変動（HRV）は迷走神経の健全性を示す指標で、高いほど健康・レジリエンスが高い。`,
    mechanismEn: `Composed of the central nervous system (brain/spinal cord) and peripheral nervous system (sensory/motor/autonomic). Sympathetic nerves release noradrenaline, raising heart rate and blood pressure (fight-or-flight). Parasympathetic nerves release acetylcholine, switching to rest-and-digest mode. The vagus nerve comprises 80% of the parasympathetic system, controlling heart, lungs, and gut. Heart rate variability (HRV) measures vagal health — higher HRV indicates greater resilience.`,
    yogaJa: `ヨガは神経系に最も深く作用する。①副交感神経優位化：長い呼気（4-7-8呼吸・Ujjayi呼吸）は迷走神経を直接刺激しHRVを上昇させる。②GABA増加：Streeter et al. (2010, J Altern Complement Med) でヨガ1時間後に脳内GABA濃度が27%上昇し、散歩グループより有意に高値。③神経可塑性：Lazar et al. (2005, NeuroReport) でヨガ経験者の皮質厚・灰白質密度が高く加齢による萎縮が抑制。④扁桃体縮小：Hölzel et al. (2011) でMBSR（8週間マインドフルネス）後に扁桃体が縮小し不安が減少。`,
    yogaEn: `Yoga has the deepest impact on the nervous system. ① Parasympathetic dominance: prolonged exhalation (4-7-8, Ujjayi breathing) directly stimulates the vagus nerve and raises HRV. ② GABA elevation: Streeter et al. (2010) found brain GABA levels rose 27% after 1 hour of yoga — significantly higher than the walking group. ③ Neuroplasticity: Lazar et al. (2005) found yoga practitioners had greater cortical thickness and grey matter density, with attenuated age-related atrophy. ④ Amygdala shrinkage: Hölzel et al. (2011) found MBSR (8 weeks) reduced amygdala volume and anxiety.`,
    scienceJa: `Porges (1994) の多重迷走神経理論：迷走神経のトーンが社会的関与・感情調節・安全感の基盤。Davidson et al. (2003, Psychosomatic Medicine)：8週間の瞑想で左前頭前野（ポジティブ感情）が活性化し免疫反応も改善。`,
    scienceEn: `Porges (1994) Polyvagal Theory: vagal tone is the foundation of social engagement, emotional regulation, and safety perception. Davidson et al. (2003): 8 weeks of meditation activated the left prefrontal cortex (positive affect) and improved immune response.`,
    poses: [
      { name: 'Savasana', effectJa: '最深の副交感神経活性化・コルチゾール消去', effectEn: 'Deepest parasympathetic activation & cortisol clearance' },
      { name: 'Legs Up the Wall', effectJa: '迷走神経刺激・HRV即時向上', effectEn: 'Vagal nerve stimulation & immediate HRV increase' },
      { name: 'Child\'s Pose', effectJa: '前頭葉鎮静・扁桃体安定化', effectEn: 'Prefrontal calming & amygdala stabilization' },
      { name: 'Pranayama (Nadi)', effectJa: '左右脳半球の統合・自律神経バランス', effectEn: 'Left-right brain hemisphere integration & ANS balance' },
    ],
    bodyParts: ['🧠', '⚡', '🫀'],
    concernLinks: [
      {
        concernId: 'stress',
        reasonJa: '自律神経系の交感神経優位（SNS過活性）が慢性ストレスの神経基盤。ノルアドレナリン・アドレナリンが持続的に分泌され心拍増加・血管収縮・消化抑制が生じる。扁桃体（恐怖・不安の中枢）が過活性化し前頭前野（理性的思考）を抑制する。',
        reasonEn: 'Sympathetic nervous system overactivation is the neural basis of chronic stress. Persistent noradrenaline/adrenaline secretion causes elevated heart rate, vasoconstriction, and digestive suppression. Amygdala hyperactivation suppresses the prefrontal cortex (rational thought).',
        yogaJa: 'ヨガの長い呼気（呼気：吸気 = 2:1）は迷走神経を直接刺激してHRVを即時改善する（Streeter et al., 2012, J Altern Complement Med）。Hölzel et al. (2011, Psychiatry Research) のMRI研究でMBSR 8週間後に扁桃体が有意に縮小し不安スコアが改善。',
        yogaEn: 'Prolonged exhalation (exhale:inhale = 2:1) directly stimulates the vagus nerve, immediately improving HRV (Streeter et al., 2012). Hölzel et al. (2011, Psychiatry Research) MRI study confirmed MBSR (8 weeks) significantly reduced amygdala volume and anxiety scores.',
        evidence: 'Streeter et al. (2012, J Altern Complement Med); Hölzel et al. (2011, Psychiatry Research: Neuroimaging)',
      },
      {
        concernId: 'sleep',
        reasonJa: 'GABAの低下と交感神経過活性が不眠の神経化学的原因。GABAは脳の主要な抑制性神経伝達物質で、GABAニューロンが睡眠導入を制御する視索前野（VLPO）を活性化する。ストレスはGABA受容体を脱感作し不眠を悪化させる。',
        reasonEn: 'Reduced GABA and sympathetic overactivation are the neurochemical causes of insomnia. GABA is the brain\'s primary inhibitory neurotransmitter — GABAergic neurons activate the VLPO (sleep control center). Stress desensitizes GABA receptors, worsening insomnia.',
        yogaJa: 'Streeter et al. (2010, J Altern Complement Med) は1時間のヨガ後に脳内GABA濃度が27%増加し（MRスペクトロスコピーで計測）、同条件の散歩グループより有意に高値であることを示した。副交感神経優位化がSNSブレーキとなり入眠を促進する。',
        yogaEn: 'Streeter et al. (2010, J Altern Complement Med) measured a 27% increase in brain GABA after 1 hour of yoga (via MR spectroscopy), significantly higher than a matched walking group. Parasympathetic dominance acts as an SNS brake, facilitating sleep onset.',
        evidence: 'Streeter et al. (2010, Journal of Alternative and Complementary Medicine)',
      },
      {
        concernId: 'focus',
        reasonJa: '集中力は背外側前頭前野（DLPFC）と前帯状皮質（ACC）の連携で制御される。慢性ストレスはコルチゾールを介してDLPFCのシナプス結合を弱め、注意制御・ワーキングメモリを低下させる（Arnsten, 2009, Nat Rev Neurosci）。',
        reasonEn: 'Focus is controlled by the DLPFC and anterior cingulate cortex (ACC). Chronic stress weakens DLPFC synaptic connections via cortisol, reducing attentional control and working memory (Arnsten, 2009, Nat Rev Neurosci).',
        yogaJa: 'Tang et al. (2007, PNAS) は5日間の統合型マインドフルネストレーニングで注意力・自己制御が有意に改善し、コルチゾールと怒りが減少することをランダム化比較試験で実証。Lazar et al. (2005) は長期瞑想者の前頭前野皮質厚が対照群より有意に厚いことを示した。',
        yogaEn: 'Tang et al. (2007, PNAS) demonstrated in an RCT that 5 days of integrative mindfulness training significantly improved attention and self-regulation while reducing cortisol. Lazar et al. (2005) showed long-term meditators had significantly greater prefrontal cortical thickness.',
        evidence: 'Tang et al. (2007, PNAS); Lazar et al. (2005, NeuroReport)',
      },
      {
        concernId: 'recovery',
        reasonJa: '心拍変動（HRV）は迷走神経活性を反映し、高HRVは自律神経系の回復能力を示す。運動後のHRV回復速度は翌日以降のパフォーマンスを予測する最も信頼性の高い生理指標の一つ（Plews et al., 2013, Int J Sports Physiol Perform）。',
        reasonEn: 'Heart rate variability (HRV) reflects vagal tone; high HRV indicates autonomic recovery capacity. Post-exercise HRV recovery speed is one of the most reliable physiological predictors of next-day performance (Plews et al., 2013, Int J Sports Physiol Perform).',
        yogaJa: 'シャヴァーサナ（屍のポーズ）の深い弛緩は迷走神経を最大限に活性化しHRVを即時回復させる。Shaffer et al. (2017, Front Public Health) のレビューでHRV向上が全身の回復力・健康予測因子であることが確認された。',
        yogaEn: 'Savasana\'s deep relaxation maximally activates the vagus nerve, immediately restoring HRV. Shaffer et al. (2017, Front Public Health) confirmed that HRV improvement is a predictor of whole-body resilience and health.',
        evidence: 'Plews et al. (2013, Int J Sports Physiol Perform); Shaffer et al. (2017, Front Public Health)',
      },
    ],
  },

  {
    id: 'endocrine',
    icon: '⚗️',
    nameJa: '内分泌系',
    nameEn: 'Endocrine System',
    taglineJa: 'ホルモンが体の全機能を調整する化学メッセンジャー',
    taglineEn: 'Hormones are chemical messengers controlling every bodily function',
    color: 'pink',
    bg: 'bg-pink-50 dark:bg-pink-950/30',
    border: 'border-pink-200 dark:border-pink-800',
    text: 'text-pink-700 dark:text-pink-300',
    badge: 'bg-pink-100 dark:bg-pink-900/50 text-pink-700 dark:text-pink-300',
    summaryJa: '慢性ストレスはコルチゾール過剰→免疫抑制・記憶障害・腹部肥満の三重苦を引き起こす。ヨガはHPA軸をリセットする。',
    summaryEn: 'Chronic stress causes cortisol excess → immune suppression, memory impairment, and visceral obesity. Yoga resets the HPA axis.',
    facts: [
      { icon: '😰', ja: 'コルチゾール（ストレスホルモン）は慢性的に高いと海馬を萎縮させる', en: 'Chronically elevated cortisol shrinks the hippocampus' },
      { icon: '🦋', ja: '甲状腺ホルモンは全細胞の代謝スピードを制御する', en: 'Thyroid hormones control metabolic rate of every cell' },
      { icon: '🌙', ja: 'メラトニンは光の刺激で制御される睡眠ホルモン', en: 'Melatonin is the sleep hormone controlled by light exposure' },
      { icon: '💉', ja: 'インスリン抵抗性は2型糖尿病・心疾患・認知症の根本原因', en: 'Insulin resistance is root cause of T2 diabetes, heart disease & dementia' },
    ],
    mechanismJa: `HPA軸（視床下部→下垂体→副腎皮質）はストレス応答の中枢で、コルチゾールを分泌する。甲状腺は代謝・体温・心拍を制御するT3/T4を産生。膵臓のβ細胞はインスリンを分泌しグルコース取り込みを調節。松果体はメラトニンを産生し概日リズムを制御。副腎髄質はアドレナリン・ノルアドレナリンで即座の戦闘・逃走反応を引き起こす。`,
    mechanismEn: `The HPA axis (hypothalamus→pituitary→adrenal cortex) is the stress command center, secreting cortisol. The thyroid produces T3/T4, controlling metabolism, body temperature, and heart rate. Pancreatic β-cells secrete insulin to regulate glucose uptake. The pineal gland produces melatonin controlling circadian rhythms. The adrenal medulla releases adrenaline/noradrenaline for immediate fight-or-flight.`,
    yogaJa: `①コルチゾール低減：West et al. (2004) でヨガ実践者の唾液コルチゾールが有意に低値。慢性ストレスによるHPA軸過活性をヨガが正常化。②甲状腺刺激：肩立ちポーズ（サルヴァンガーサナ）・魚のポーズは頸部への血流を増加させ甲状腺を機械的に刺激。③インスリン感受性改善：Innes et al. (2005) でヨガがインスリン抵抗性マーカーを有意改善。④成長ホルモン・テストステロン：倒立・強度ポーズ実践後に成長ホルモンが一時的に上昇。⑤メラトニン：ヨガの深呼吸と弛緩が松果体の活性を高め夜間メラトニン分泌を増加。`,
    yogaEn: `① Cortisol reduction: West et al. (2004) found significantly lower salivary cortisol in yoga practitioners. Yoga normalizes HPA axis hyperactivation from chronic stress. ② Thyroid stimulation: Shoulderstand and Fish Pose increase cervical blood flow and mechanically compress the thyroid. ③ Insulin sensitivity: Innes et al. (2005) found yoga significantly improved insulin resistance markers. ④ Growth hormone/testosterone: inversions and power poses transiently elevate GH. ⑤ Melatonin: deep yogic breathing and relaxation enhance pineal activity, increasing nocturnal melatonin secretion.`,
    scienceJa: `McEwen (1998) の「アロスタティック負荷」概念：慢性ストレスによる累積的消耗が全身疾患の基盤。Sapolsky (2004)「Why Zebras Don't Get Ulcers」：人間はシマウマと違い将来を心配しHPA軸を慢性的に活性化する。`,
    scienceEn: `McEwen (1998) "allostatic load": cumulative wear from chronic stress is the foundation of systemic disease. Sapolsky (2004) "Why Zebras Don't Get Ulcers": unlike zebras, humans worry about the future, chronically activating the HPA axis.`,
    poses: [
      { name: 'Shoulderstand', effectJa: '甲状腺・副甲状腺への血流促進', effectEn: 'Increases blood flow to thyroid & parathyroid' },
      { name: 'Fish Pose', effectJa: '甲状腺刺激・胸部開放・メラトニン促進', effectEn: 'Thyroid stimulation & melatonin promotion' },
      { name: 'Restorative Yoga', effectJa: 'HPA軸リセット・コルチゾール正常化', effectEn: 'HPA axis reset & cortisol normalization' },
      { name: 'Forward Fold', effectJa: '副腎疲労回復・インスリン感受性改善', effectEn: 'Adrenal recovery & insulin sensitivity improvement' },
    ],
    bodyParts: ['⚗️', '🦋', '🧪'],
    concernLinks: [
      {
        concernId: 'stress',
        reasonJa: '慢性ストレスはHPA軸（視床下部-下垂体-副腎皮質軸）を持続的に活性化しコルチゾールを過剰分泌させる。コルチゾールは海馬を萎縮させ、免疫細胞を抑制し、腹部脂肪蓄積を促進する「三重苦」を引き起こす（McEwen, 2007, Physiol Rev）。',
        reasonEn: 'Chronic stress persistently activates the HPA axis, causing cortisol excess. Cortisol shrinks the hippocampus, suppresses immune cells, and promotes visceral fat accumulation — a "triple burden" (McEwen, 2007, Physiol Rev).',
        yogaJa: 'Thirthalli et al. (2013, Indian J Psychiatry) のRCTでヨガがコルチゾール、ACTH（副腎皮質刺激ホルモン）をプラセボより有意に低下させた。リストラティブヨガと陰ヨガはHPA軸の過活性を最も効果的に鎮静させ、内分泌系を根本からリセットする。',
        yogaEn: 'An RCT by Thirthalli et al. (2013, Indian J Psychiatry) found yoga significantly reduced cortisol and ACTH vs placebo. Restorative and yin yoga most effectively calm HPA axis hyperactivity, fundamentally resetting the endocrine system.',
        evidence: 'Thirthalli et al. (2013, Indian J Psychiatry); McEwen (2007, Physiol Rev)',
      },
      {
        concernId: 'sleep',
        reasonJa: 'コルチゾールは本来朝高く夜低い概日リズムを持つ。慢性ストレスでこのリズムが平坦化（夜間コルチゾール高止まり）すると松果体のメラトニン産生が抑制され不眠となる（Leproult et al., 1997, Sleep）。',
        reasonEn: 'Cortisol normally follows a circadian rhythm — high in the morning, low at night. Chronic stress flattens this rhythm (elevated nocturnal cortisol), suppressing melatonin production in the pineal gland and causing insomnia (Leproult et al., 1997, Sleep).',
        yogaJa: '夕方のヨガはコルチゾールの夜間低下を促進し、メラトニン分泌を回復させる。Khalsa (2004, Appl Psychophysiol Biofeedback) のパイロット試験でヨガが慢性不眠患者の総睡眠時間・睡眠効率・入眠潜時を有意に改善した。',
        yogaEn: 'Evening yoga promotes the nocturnal cortisol decline and restores melatonin secretion. Khalsa (2004, Appl Psychophysiol Biofeedback) demonstrated in a pilot trial that yoga significantly improved total sleep time, sleep efficiency, and sleep onset latency in chronic insomnia patients.',
        evidence: 'Leproult et al. (1997, Sleep); Khalsa SB (2004, Appl Psychophysiol Biofeedback)',
      },
      {
        concernId: 'recovery',
        reasonJa: 'コルチゾールは筋タンパクを分解する異化ホルモンで、過剰だと筋回復を妨げる。反対に成長ホルモン（GH）は睡眠中のノンレム深睡眠時に最も多く分泌され、筋肉・骨の修復（同化）を促す。コルチゾール/GH比が回復の質を決定する。',
        reasonEn: 'Cortisol is a catabolic hormone that breaks down muscle protein — excess cortisol impairs muscle recovery. Conversely, growth hormone (GH) is maximally secreted during slow-wave sleep, promoting tissue repair (anabolism). The cortisol/GH ratio determines recovery quality.',
        yogaJa: 'ヨガによるコルチゾール低減が同化/異化ホルモンバランスを回復させる。さらに睡眠質の改善（上記）が深睡眠中のGH分泌を最大化し、筋・骨の修復を加速する。Innes & Vincent (2007, eCAM) でヨガが内分泌・代謝マーカーを複数改善。',
        yogaEn: 'Yoga\'s cortisol reduction restores anabolic/catabolic hormone balance. Improved sleep quality (see above) maximizes GH secretion during deep sleep, accelerating tissue repair. Innes & Vincent (2007, eCAM) found yoga improved multiple endocrine and metabolic markers.',
        evidence: 'Innes & Vincent (2007, eCAM — Evidence-based Complementary and Alternative Medicine)',
      },
      {
        concernId: 'focus',
        reasonJa: 'コルチゾールは前頭前野（PFC）のシナプス可塑性を低下させ、ドーパミン・セロトニン受容体の発現を抑制する。Arnsten (2009, Nat Rev Neurosci) は高コルチゾールが「PFCを実質的にオフラインにする」と表現し、集中力・判断力・記憶力の著しい低下を引き起こすと説明。',
        reasonEn: 'Cortisol reduces synaptic plasticity in the prefrontal cortex (PFC) and suppresses dopamine/serotonin receptor expression. Arnsten (2009, Nat Rev Neurosci) described high cortisol as effectively "taking the PFC offline," causing dramatic declines in focus, judgment, and memory.',
        yogaJa: 'コルチゾール低減によるPFC機能回復が集中力・作業記憶・意思決定を改善する。Gothe et al. (2013, J Phys Act Health) でヨガ後に実行機能（ストループ課題・N-back課題）の成績が有意に向上した。',
        yogaEn: 'Cortisol reduction restores PFC function, improving focus, working memory, and decision-making. Gothe et al. (2013) found significantly improved executive function (Stroop task, N-back task) performance after yoga.',
        evidence: 'Arnsten (2009, Nat Rev Neurosci); Gothe et al. (2013, J Phys Act Health)',
      },
    ],
  },

  {
    id: 'respiratory',
    icon: '🫁',
    nameJa: '呼吸器系',
    nameEn: 'Respiratory System',
    taglineJa: '1日2万回の呼吸が自律神経と脳を直接制御する',
    taglineEn: '20,000 daily breaths directly control the autonomic nervous system and brain',
    color: 'sky',
    bg: 'bg-sky-50 dark:bg-sky-950/30',
    border: 'border-sky-200 dark:border-sky-800',
    text: 'text-sky-700 dark:text-sky-300',
    badge: 'bg-sky-100 dark:bg-sky-900/50 text-sky-700 dark:text-sky-300',
    summaryJa: '鼻呼吸は一酸化窒素（NO）を産生し血管を拡張。口呼吸より血中酸素濃度が10〜20%高くなる。',
    summaryEn: 'Nasal breathing produces nitric oxide (NO), dilating blood vessels. It achieves 10–20% higher blood oxygen than mouth breathing.',
    facts: [
      { icon: '🫧', ja: '肺胞は約3億個、広げると100㎡（テニスコート半面）', en: '~300 million alveoli; surface area equals half a tennis court when spread' },
      { icon: '🌬️', ja: '横隔膜は呼吸の主役、体積の70%を担う最重要呼吸筋', en: 'The diaphragm drives 70% of breathing volume — the most critical respiratory muscle' },
      { icon: '🔵', ja: '一酸化窒素（NO）は鼻腔で産生され血管拡張・免疫・抗菌作用を持つ', en: 'Nitric oxide (NO) is produced in nasal cavities — vasodilates, boosts immunity, and kills pathogens' },
      { icon: '⚖️', ja: 'CO2は単なる廃棄物ではなく酸素放出を制御する「ボーア効果」の主役', en: 'CO2 is not just waste — it controls oxygen release via the Bohr effect' },
    ],
    mechanismJa: `肺胞でのガス交換：酸素が赤血球ヘモグロビンに結合し全身へ運搬、CO2が廃棄される。横隔膜が収縮（下降）すると胸腔が広がり空気が流入。呼気の長さが副交感神経活性化の量を決定する—長い呼気ほど迷走神経ブレーキが強くかかる。ボーア効果：血中CO2が高いほどヘモグロビンから酸素が解放されやすくなる。過換気（CO2低下）は逆に組織への酸素供給を減らす逆説が起きる。`,
    mechanismEn: `Gas exchange in alveoli: oxygen binds to hemoglobin in red blood cells for systemic transport; CO2 is expelled. Diaphragm contraction (downward movement) expands the thoracic cavity, drawing in air. The length of exhalation determines the amount of parasympathetic activation — longer exhalation = stronger vagal brake. Bohr effect: higher blood CO2 facilitates oxygen release from hemoglobin. Paradoxically, hyperventilation (low CO2) reduces tissue oxygen delivery.`,
    yogaJa: `プラナヤマはすべての呼吸器機能を意図的に操作する技術。①ウジャイ呼吸：声門を狭めることで呼吸抵抗を増やし肺胞の換気量を均一化、副交感神経を活性化。②片鼻呼吸（ナーディシューダナ）：右鼻（太陽・交感神経）と左鼻（月・副交感神経）を交互に刺激し自律神経を均衡化。③カパラバーティ：強制呼気が横隔膜を強化し肺残気量を排出、交感神経・エネルギーを高める。④4-7-8呼吸：呼気8秒で迷走神経を強力に刺激、不安発作・不眠に即効。横隔膜呼吸の習慣化で肺活量が最大30%改善する報告がある。`,
    yogaEn: `Pranayama is the systematic technique for intentional control of all respiratory functions. ① Ujjayi breathing: narrowing the glottis increases resistance, equalizes alveolar ventilation, and activates the parasympathetic nervous system. ② Nadi Shodhana (alternate nostril): alternately stimulates the right nostril (sun/sympathetic) and left nostril (moon/parasympathetic) to balance the ANS. ③ Kapalabhati: forced exhalation strengthens the diaphragm, expels residual lung volume, and activates sympathetic/energy systems. ④ 4-7-8 breathing: 8-second exhalation powerfully stimulates the vagus — effective for acute anxiety and insomnia. Diaphragmatic breathing training can improve lung capacity by up to 30%.`,
    scienceJa: `Nestor (2020)「Breath」：現代人の慢性口呼吸が睡眠時無呼吸・歯列不正・不安を引き起こす。Bhambhani & Bhambhani (2006)：プラナヤマが最大酸素摂取量（VO2max）を有意に改善。McKeown「酸素のパラドックス」：適度なCO2耐性が組織酸素化の鍵。`,
    scienceEn: `Nestor (2020) "Breath": chronic mouth breathing in modern humans causes sleep apnea, dental malocclusion, and anxiety. Bhambhani & Bhambhani (2006): pranayama significantly improves VO2max. McKeown "The Oxygen Advantage": moderate CO2 tolerance is key to tissue oxygenation.`,
    poses: [
      { name: 'Pranayama (Ujjayi)', effectJa: '迷走神経活性・肺活量増大・横隔膜強化', effectEn: 'Vagal activation, lung capacity & diaphragm strengthening' },
      { name: 'Camel Pose', effectJa: '胸郭最大伸展・肺の前面を全開放', effectEn: 'Maximum thoracic expansion & full anterior lung opening' },
      { name: 'Fish Pose', effectJa: '胸郭伸展・肋間筋ストレッチ・気道拡張', effectEn: 'Thoracic expansion & intercostal stretch' },
      { name: 'Nadi Shodhana', effectJa: '左右半球統合・自律神経均衡・NO産生促進', effectEn: 'Brain hemisphere integration & nitric oxide production' },
    ],
    bodyParts: ['🫁', '🌬️', '💨'],
    concernLinks: [
      {
        concernId: 'stress',
        reasonJa: 'ストレス→浅く速い呼吸（胸式過換気）→血中CO2低下→脳血管収縮→不安増幅の悪循環が生じる。呼吸数は自律神経状態の最も敏感な生理指標であり、ストレス下では通常の12〜15回/分から25回/分以上に増加する。',
        reasonEn: 'Stress → shallow rapid breathing (hyperventilation) → low blood CO2 → cerebral vasoconstriction → amplified anxiety — a vicious cycle. Breathing rate is the most sensitive physiological index of autonomic state; under stress it rises from normal 12–15/min to over 25/min.',
        yogaJa: 'Zaccaro et al. (2018, Front Hum Neurosci) の体系的レビューで、スロー呼吸（6回/分以下）が交感神経活性を低下させHRVと副交感神経を著しく改善することを確認。ウジャイ呼吸（5〜6回/分）はこの理想的スロー呼吸を実現するヨガの核心技術。',
        yogaEn: 'Zaccaro et al. (2018, Front Hum Neurosci) systematic review confirmed that slow breathing (≤6/min) significantly reduces sympathetic activation and improves HRV and parasympathetic tone. Ujjayi breathing (5–6/min) is yoga\'s core technique for achieving this optimal slow breathing.',
        evidence: 'Zaccaro et al. (2018, Frontiers in Human Neuroscience)',
      },
      {
        concernId: 'focus',
        reasonJa: '鼻呼吸は副鼻腔で一酸化窒素（NO）を産生し、脳への血流を増加させる。Lundberg et al. (1996, Nature) が鼻腔でのNO産生を実証。またCO2レベルが血中酸素のヘモグロビンからの解放を制御するボーア効果により、適切なCO2維持が脳の酸素化を最大化する。',
        reasonEn: 'Nasal breathing produces nitric oxide (NO) in paranasal sinuses, increasing cerebral blood flow. Lundberg et al. (1996, Nature) demonstrated nasal NO production. The Bohr effect — CO2 controls oxygen release from hemoglobin — means maintaining adequate CO2 maximizes brain oxygenation.',
        yogaJa: 'ナーディ・ショーダナ（交互鼻孔呼吸）は両鼻腔を均等に活性化してNO産生を最大化し、左右大脳半球の統合を促す。Telles et al. (1994, Indian J Physiol Pharmacol) で右鼻孔呼吸が空間認知タスク成績を改善することを確認（交感神経-左脳活性化）。',
        yogaEn: 'Nadi Shodhana (alternate nostril breathing) activates both nasal passages equally, maximizing NO production and promoting left-right brain hemisphere integration. Telles et al. (1994, Indian J Physiol Pharmacol) confirmed right nostril breathing improves spatial tasks (sympathetic/left-brain activation).',
        evidence: 'Lundberg et al. (1996, Nature); Telles et al. (1994, Indian J Physiol Pharmacol)',
      },
      {
        concernId: 'sleep',
        reasonJa: '呼吸は自律神経系を通じて睡眠の深さを直接制御する。横隔膜呼吸は迷走神経の求心性線維を刺激し、副交感神経優位をもたらして入眠を促進する。Jerath et al. (2006, Med Hypotheses) はプラナヤマが自律神経を介した睡眠誘導機構を活性化すると提唱。',
        reasonEn: 'Breathing directly controls sleep depth via the autonomic nervous system. Diaphragmatic breathing stimulates vagal afferent fibers, inducing parasympathetic dominance and facilitating sleep onset. Jerath et al. (2006, Med Hypotheses) proposed that pranayama activates autonomic sleep-induction pathways.',
        yogaJa: '4-7-8呼吸（吸気4拍・保持7拍・呼気8拍）は長い呼気で迷走神経を強力に刺激し不安発作・入眠困難に即効性がある。就寝前のヨガ・ニードラは副交感神経を極限まで高め、睡眠導入時間（入眠潜時）を有意に短縮させることが複数の研究で示されている。',
        yogaEn: '4-7-8 breathing (inhale 4, hold 7, exhale 8) powerfully stimulates the vagus via prolonged exhalation, with immediate effects on acute anxiety and sleep-onset difficulty. Pre-sleep Yoga Nidra maximally activates the parasympathetic system, with multiple studies showing significant reduction in sleep onset latency.',
        evidence: 'Jerath et al. (2006, Medical Hypotheses); Khalsa SB (2004, Appl Psychophysiol Biofeedback)',
      },
      {
        concernId: 'recovery',
        reasonJa: '最大酸素摂取量（VO2max）は有酸素性回復能力の金標準指標であり、横隔膜の筋力・肺活量・呼吸効率が決定因子の一つ。呼吸筋の疲労が全身の疲労感に大きく寄与することが運動生理学的に示されている。',
        reasonEn: 'VO2max is the gold standard measure of aerobic recovery capacity — diaphragm strength, lung capacity, and breathing efficiency are key determinants. Exercise physiology research demonstrates that respiratory muscle fatigue significantly contributes to whole-body fatigue.',
        yogaJa: 'カパラバーティ（強制呼気の繰り返し）は横隔膜・腹筋の筋力を高め呼吸効率を向上させる。Bhambhani & Singh (1985, Physiother Can) でプラナヤマの継続実践がVO2max指標を改善することが示された。',
        yogaEn: 'Kapalabhati (repeated forceful exhalations) strengthens the diaphragm and abdominal muscles, improving breathing efficiency. Bhambhani & Singh (1985, Physiother Can) demonstrated that sustained pranayama practice improves VO2max indices.',
        evidence: 'Bhambhani & Singh (1985, Physiotherapy Canada)',
      },
    ],
  },

  {
    id: 'cardiovascular',
    icon: '🫀',
    nameJa: '心臓・血管系',
    nameEn: 'Cardiovascular System',
    taglineJa: '心臓は1日10万回拍動し約5Lの血液を全身に循環させる',
    taglineEn: 'The heart beats 100,000 times daily, circulating ~5L of blood throughout the body',
    color: 'red',
    bg: 'bg-red-50 dark:bg-red-950/30',
    border: 'border-red-200 dark:border-red-800',
    text: 'text-red-700 dark:text-red-300',
    badge: 'bg-red-100 dark:bg-red-900/50 text-red-700 dark:text-red-300',
    summaryJa: 'ヨガは収縮期血圧を平均5〜10mmHg低下させる。薬剤1種に匹敵する降圧効果が複数のメタ解析で確認されている。',
    summaryEn: 'Yoga lowers systolic blood pressure by 5–10 mmHg on average — equivalent to one antihypertensive medication, confirmed by multiple meta-analyses.',
    facts: [
      { icon: '💓', ja: '心拍変動（HRV）は心臓の適応力・健康状態を示す最重要指標', en: 'Heart rate variability (HRV) is the key indicator of cardiac adaptability and health' },
      { icon: '🩸', ja: '血管内皮細胞はNOを産生し血管を柔軟に保つ—ストレスで機能低下', en: 'Endothelial cells produce NO to keep vessels supple — impaired by chronic stress' },
      { icon: '🔄', ja: '逆転ポーズは静脈還流を重力補助で増加させ心臓負荷を軽減', en: 'Inversions use gravity to boost venous return and reduce cardiac workload' },
      { icon: '❤️‍🔥', ja: '動的ヨガは心肺機能を向上させ安静時心拍数を低下させる', en: 'Dynamic yoga improves cardiopulmonary fitness and lowers resting heart rate' },
    ],
    mechanismJa: `心臓は左心室→大動脈→全身毛細血管→静脈→右心房→肺→左心房→左心室のループを1分間に60〜80回繰り返す。内皮細胞はNO（一酸化窒素）を産生し血管平滑筋を弛緩させて血圧を調整。慢性ストレス→コルチゾール・アドレナリン→血管収縮・内皮機能障害→動脈硬化の連鎖が心疾患の主経路。HRVは迷走神経活性を反映し、高HRVは心臓が様々な要求に素早く適応できる証拠。`,
    mechanismEn: `The heart cycles 60–80 times per minute: left ventricle → aorta → systemic capillaries → veins → right atrium → lungs → left atrium → left ventricle. Endothelial cells produce NO to relax vascular smooth muscle and regulate blood pressure. Chronic stress → cortisol/adrenaline → vasoconstriction → endothelial dysfunction → atherosclerosis — the main pathway to heart disease. HRV reflects vagal tone; high HRV indicates the heart can rapidly adapt to diverse demands.`,
    yogaJa: `①血圧低下：Hagins et al. (2007) メタ解析でヨガが収縮期BP 5mmHg、拡張期BP 3.9mmHg低下。②HRV向上：Sun Salutation・ゆっくり呼吸ヨガ後にHRVが即時改善。③内皮機能改善：ヨガによるNO産生増加→血管柔軟性回復。④コレステロール改善：Ornish Program（ヨガ+食事）でLDL 24.4%低下・冠動脈プラーク退縮。⑤逆転ポーズ（ダウンドック・脚上げ）：重力逆用で静脈還流を増加させ心臓の仕事量を一時的に軽減、迷走神経を刺激して安静時心拍を低下。`,
    yogaEn: `① Blood pressure: Hagins et al. (2007) meta-analysis found yoga lowered SBP by 5 mmHg and DBP by 3.9 mmHg. ② HRV improvement: Sun Salutation and slow-breathing yoga immediately improve HRV. ③ Endothelial function: yoga-induced NO production restores vascular flexibility. ④ Cholesterol: Ornish Program (yoga + diet) reduced LDL by 24.4% and reversed coronary plaque. ⑤ Inversions (Downdog, Legs Up): reverse gravity boosts venous return, reducing cardiac workload, and stimulate the vagus to lower resting heart rate.`,
    scienceJa: `Ornish et al. (1990, Lancet)：ライフスタイル変更（ヨガ含む）のみで冠動脈疾患が退縮した画期的研究。AHA (2019)：ヨガを心臓リハビリテーションの補完療法として正式推奨。`,
    scienceEn: `Ornish et al. (1990, Lancet): landmark study showing lifestyle changes including yoga reversed coronary artery disease without drugs. AHA (2019): officially endorsed yoga as complementary therapy in cardiac rehabilitation.`,
    poses: [
      { name: 'Sun Salutation', effectJa: '心肺機能向上・安静時心拍低下・HRV改善', effectEn: 'Cardiopulmonary conditioning & resting HR reduction' },
      { name: 'Legs Up the Wall', effectJa: '静脈還流促進・心臓負荷軽減・血圧降下', effectEn: 'Venous return boost & blood pressure reduction' },
      { name: 'Bridge Pose', effectJa: '心臓より下肢を高く保ち静脈還流を助ける', effectEn: 'Assists venous return with legs above heart level' },
      { name: 'Slow Pranayama', effectJa: '迷走神経活性でHRV向上・降圧', effectEn: 'Vagal activation → HRV increase & BP reduction' },
    ],
    bodyParts: ['🫀', '🩸', '💓'],
    concernLinks: [
      {
        concernId: 'stress',
        reasonJa: '交感神経亢進→末梢血管収縮→血圧上昇→血管内皮障害のカスケードがストレス性高血圧の機序。内皮細胞からのNO産生障害が動脈硬化の最初期変化。Kivimäki et al. (2012, Lancet) の大規模コホートでストレスが心臓病リスクを23%増大させることが示された。',
        reasonEn: 'Sympathetic activation → peripheral vasoconstriction → hypertension → endothelial damage is the cascade of stress-induced hypertension. Impaired NO production from endothelial cells is the earliest change in atherosclerosis. Kivimäki et al. (2012, Lancet) showed stress increases heart disease risk by 23% in a large cohort.',
        yogaJa: 'Cramer et al. (2014, J Hypertens) のメタ解析（17 RCT）でヨガが収縮期血圧を平均−4.2 mmHg、拡張期血圧を−3.2 mmHg低下させることが証明された。副交感神経活性化によるNO産生回復が内皮機能を改善する。',
        yogaEn: 'Cramer et al. (2014, J Hypertens) meta-analysis (17 RCTs) proved yoga lowers systolic BP by −4.2 mmHg and diastolic by −3.2 mmHg. Parasympathetic-induced NO restoration improves endothelial function.',
        evidence: 'Cramer et al. (2014, Journal of Hypertension); Kivimäki et al. (2012, Lancet)',
      },
      {
        concernId: 'recovery',
        reasonJa: '心拍出量（心拍数×一回拍出量）が全身の酸素・栄養素の運搬量を決定する。安静時心拍数が低い（心臓が効率的）ほど運動後の循環回復が速い。迷走神経トーン高値が心臓の適応力・回復力を示す。',
        reasonEn: 'Cardiac output (heart rate × stroke volume) determines systemic oxygen/nutrient delivery. Lower resting heart rate (efficient heart) means faster circulatory recovery post-exercise. High vagal tone indicates cardiac adaptability and recovery capacity.',
        yogaJa: '逆転ポーズ（脚上げ・ダウンドッグ）は重力を利用して静脈還流を増加させ心臓の仕事量を効率化する。太陽礼拝の繰り返しは有酸素性心拍出量を高め、安静時心拍数を長期的に低下させる（Bock et al., 2012, Int J Yoga）。',
        yogaEn: 'Inversions (Legs Up, Downdog) use gravity to increase venous return and improve cardiac efficiency. Repeated Sun Salutations improve aerobic cardiac output and long-term lower resting heart rate (Bock et al., 2012, Int J Yoga).',
        evidence: 'Cramer et al. (2014, J Hypertens); Ornish et al. (1990, Lancet)',
      },
      {
        concernId: 'sleep',
        reasonJa: 'HRV（心拍変動）は睡眠の質と強い正の相関を示す。夜間HRVが低い人は深睡眠が少なく疲労回復が不十分。就寝前の交感神経過活性（心拍数高値・HRV低値）が入眠困難の心臓血管的指標。',
        reasonEn: 'HRV shows a strong positive correlation with sleep quality. People with low nocturnal HRV have less deep sleep and insufficient recovery. Pre-sleep sympathetic overactivation (high heart rate, low HRV) is the cardiovascular marker of sleep-onset difficulty.',
        yogaJa: '就寝前のリストラティブヨガはHRVを高め副交感神経を優位にして心臓を「睡眠モード」に切り替える。Markil et al. (2012, J Strength Cond Res) でヨガ・ニードラがHRVを有意に改善し副交感神経指標（HF成分）を増加させた。',
        yogaEn: 'Pre-sleep restorative yoga raises HRV and parasympathetic tone, switching the heart into "sleep mode." Markil et al. (2012, J Strength Cond Res) found Yoga Nidra significantly improved HRV and increased the parasympathetic HF component.',
        evidence: 'Markil et al. (2012, J Strength Cond Res)',
      },
    ],
  },

  {
    id: 'lymphatic',
    icon: '🛡️',
    nameJa: 'リンパ・免疫系',
    nameEn: 'Lymphatic & Immune System',
    taglineJa: 'ポンプを持たないリンパは筋肉と呼吸だけが動かせる',
    taglineEn: 'Lymph has no pump — only muscles and breathing can move it',
    color: 'emerald',
    bg: 'bg-emerald-50 dark:bg-emerald-950/30',
    border: 'border-emerald-200 dark:border-emerald-800',
    text: 'text-emerald-700 dark:text-emerald-300',
    badge: 'bg-emerald-100 dark:bg-emerald-900/50 text-emerald-700 dark:text-emerald-300',
    summaryJa: 'ヨガの逆転ポーズ・ねじりは「手動ポンプ」としてリンパ流を促進し、免疫細胞の循環と老廃物排出を加速する。',
    summaryEn: 'Inversions and twists act as "manual pumps," accelerating lymph flow, immune cell circulation, and waste clearance.',
    facts: [
      { icon: '🔀', ja: 'リンパ管は体中に張り巡らされ組織液・老廃物・免疫細胞を運搬', en: 'Lymphatic vessels carry tissue fluid, waste, and immune cells throughout the body' },
      { icon: '🌰', ja: 'リンパ節（約600個）でT細胞・B細胞が病原体を認識・排除', en: '~600 lymph nodes where T & B cells recognize and eliminate pathogens' },
      { icon: '🧹', ja: '脳のグリンパティック系（睡眠中に活性化）はアミロイドβを洗浄する', en: 'The brain\'s glymphatic system (active during sleep) clears amyloid-β and waste' },
      { icon: '😰', ja: 'ストレスがNK細胞活性を低下させ免疫監視能を弱める', en: 'Stress suppresses NK cell activity, weakening immune surveillance' },
    ],
    mechanismJa: `リンパ系は心臓のようなポンプを持たず、骨格筋の収縮・横隔膜の呼吸運動・体位変換によってリンパ液が流れる。リンパ節でナイーブT細胞が樹状細胞から抗原情報を受け取り活性化。胸腺でT細胞が成熟、骨髄でB細胞が産生される。慢性ストレスはコルチゾールを介してリンパ球を抑制し自然免疫・獲得免疫の両方を弱体化させる。腸管リンパ（GALT）は全免疫細胞の70%を収容する最大の免疫器官。`,
    mechanismEn: `The lymphatic system has no dedicated pump — flow depends on skeletal muscle contraction, diaphragmatic breathing, and postural changes. In lymph nodes, naive T cells receive antigen information from dendritic cells and activate. T cells mature in the thymus; B cells are produced in bone marrow. Chronic stress suppresses lymphocytes via cortisol, weakening both innate and adaptive immunity. The gut-associated lymphoid tissue (GALT) houses 70% of all immune cells.`,
    yogaJa: `①リンパポンプ効果：ヴィンヤサの筋収縮→弛緩サイクルが四肢のリンパポンプとして機能。②逆転ポーズ（ダウンドッグ・肩立ち）：重力を逆転させ下肢に溜まったリンパを中枢に還流。③ねじりポーズ：腹腔・腸間膜リンパ節を搾り出し免疫細胞を循環に出す。④深呼吸：横隔膜の大幅な収縮・弛緩が胸管（最大リンパ管）の流れを加速。⑤NK細胞活性化：Falkenberg et al. (2018) でヨガが自然免疫活性化マーカーを改善。⑥睡眠改善（ヨガ→良質睡眠）→グリンパティック系活性化→脳老廃物排出。`,
    yogaEn: `① Lymph pump: vinyasa muscle contraction-relaxation cycles function as limb lymphatic pumps. ② Inversions (Downdog, Shoulderstand): reverse gravity to drain lymph pooled in limbs back to the core. ③ Twisting poses: wring out abdominal and mesenteric lymph nodes, releasing immune cells into circulation. ④ Deep breathing: large diaphragm excursions accelerate flow through the thoracic duct (largest lymph vessel). ⑤ NK cell activation: Falkenberg et al. (2018) found yoga improved innate immune activation markers. ⑥ Sleep improvement (yoga → quality sleep) → glymphatic activation → brain waste clearance.`,
    scienceJa: `Kiecolt-Glaser et al. (2010) でヨガ実践者のIL-6（炎症マーカー）が低値。脳のグリンパティックシステム（Nedergaard, 2013, Science）：睡眠中に脳脊髄液が脳実質を洗浄、アルツハイマー予防に関連。`,
    scienceEn: `Kiecolt-Glaser et al. (2010): yoga practitioners had lower IL-6 (inflammation marker). Brain glymphatic system (Nedergaard, 2013, Science): during sleep, CSF flushes brain tissue — linked to Alzheimer's prevention.`,
    poses: [
      { name: 'Downward Dog', effectJa: '全身リンパ還流・NK細胞活性化', effectEn: 'Full-body lymph drainage & NK cell activation' },
      { name: 'Seated Spinal Twist', effectJa: '腸管リンパ節刺激・免疫細胞放出', effectEn: 'Mesenteric lymph node compression & immune cell release' },
      { name: 'Shoulderstand', effectJa: '下肢リンパ逆流・脾臓への血流増加', effectEn: 'Lower limb lymph reversal & spleen blood flow' },
      { name: 'Yoga Nidra', effectJa: '睡眠質改善→グリンパティック活性化', effectEn: 'Sleep quality → glymphatic activation & brain cleansing' },
    ],
    bodyParts: ['🛡️', '🧬', '🌰'],
    concernLinks: [
      {
        concernId: 'stress',
        reasonJa: 'コルチゾールはNK（ナチュラルキラー）細胞・T細胞・B細胞の増殖と活性を抑制し、免疫監視能を弱める。慢性ストレスは炎症性サイトカイン（IL-6、TNF-α）を増加させ、一方で適応免疫（ウイルス・がん対応）を低下させるという逆説的な免疫失調を引き起こす。',
        reasonEn: 'Cortisol suppresses NK cell, T cell, and B cell proliferation and activity, weakening immune surveillance. Chronic stress paradoxically increases inflammatory cytokines (IL-6, TNF-α) while reducing adaptive immunity (against viruses and cancer).',
        yogaJa: 'Kiecolt-Glaser et al. (2010, Psychosom Med) でヨガがIL-6などの炎症マーカーを有意に低下させ免疫調整効果を示した。さらにNK細胞活性の改善がヨガ実践者で確認されており、ストレス抑制を通じた免疫系の正常化が機序。',
        yogaEn: 'Kiecolt-Glaser et al. (2010, Psychosom Med) showed yoga significantly reduced IL-6 and other inflammatory markers, demonstrating immune-modulating effects. NK cell activity improvement has been confirmed in yoga practitioners, with the mechanism being immune normalization via stress suppression.',
        evidence: 'Kiecolt-Glaser et al. (2010, Psychosomatic Medicine)',
      },
      {
        concernId: 'recovery',
        reasonJa: 'リンパ系は運動後の筋組織から代謝老廃物（乳酸、炎症物質）を回収する経路でもある。リンパ流量は骨格筋の収縮・横隔膜の動き・体位によって変化し、ポンプがないため自発的な運動が必須。',
        reasonEn: 'The lymphatic system is also the recovery pathway that collects metabolic waste (lactate, inflammatory mediators) from post-exercise muscle tissue. Lymph flow changes with skeletal muscle contraction, diaphragm movement, and posture — with no pump, voluntary movement is essential.',
        yogaJa: 'ヴィンヤサの収縮-弛緩サイクルがリンパポンプとして機能し、逆転ポーズが四肢のリンパを体中枢へ戻す。ねじりポーズは腸間膜リンパ節を絞ることで免疫細胞と老廃物処理を加速させる。',
        yogaEn: 'Vinyasa contraction-relaxation cycles function as limb lymphatic pumps; inversions return limb lymph to the central circulation. Twisting poses compress mesenteric lymph nodes, accelerating immune cell circulation and waste processing.',
        evidence: 'Mortimer (1990, J Clin Oncol) — muscle pump and lymphatic flow; Kiecolt-Glaser et al. (2010)',
      },
      {
        concernId: 'eyes',
        reasonJa: '目の疲れ（眼精疲労）は眼球周囲の筋肉緊張だけでなく、眼窩周囲のリンパ・静脈うっ滞も原因。長時間の集中でまばたきが減少し（健康な20回/分→PCモニター時4〜5回/分）、眼球表面のリンパ循環が滞る。',
        reasonEn: 'Eye fatigue (asthenopia) is caused not only by periocular muscle tension but also by lymphatic and venous stasis around the orbit. Prolonged screen time reduces blinking (healthy 20/min → 4–5/min at screen), stagnating lymphatic circulation over the ocular surface.',
        yogaJa: '逆転ポーズ（脚上げの壁・ダウンドッグ）は顔面・眼窩周囲のリンパ・静脈うっ滞を重力を利用して解消する。シャヴァーサナでの完全閉眼と外眼筋の弛緩が眼精疲労を直接解消し、深呼吸が眼部への血流と酸素供給を回復させる。',
        yogaEn: 'Inversions (Legs Up the Wall, Downdog) use gravity to clear lymphatic and venous stasis around the face and orbits. Complete eye closure and extraocular muscle relaxation in Savasana directly relieves asthenopia, while deep breathing restores blood flow and oxygenation to the eyes.',
        evidence: 'Anatomically grounded mechanism; Okamoto et al. (2013, J Phys Ther Sci) — yoga reduces visual fatigue markers',
      },
    ],
  },

  {
    id: 'digestive',
    icon: '🌿',
    nameJa: '消化器系',
    nameEn: 'Digestive System',
    taglineJa: '腸は「第2の脳」— 神経細胞は脳の次に多く、独立して機能する',
    taglineEn: 'The gut is the "second brain" — its neural cells outnumber those of the spinal cord',
    color: 'amber',
    bg: 'bg-amber-50 dark:bg-amber-950/30',
    border: 'border-amber-200 dark:border-amber-800',
    text: 'text-amber-700 dark:text-amber-300',
    badge: 'bg-amber-100 dark:bg-amber-900/50 text-amber-700 dark:text-amber-300',
    summaryJa: '腸内細菌は脳内セロトニンの90%を産生する。ヨガのストレス低減は腸内フローラを健全に保ち、うつ病リスクを下げる。',
    summaryEn: 'Gut bacteria produce 90% of the brain\'s serotonin. Yoga\'s stress reduction maintains healthy microbiome and lowers depression risk.',
    facts: [
      { icon: '🧫', ja: '腸内細菌叢は約100兆個、遺伝子数は人間の150倍以上', en: '~100 trillion gut bacteria with 150x more genes than the human genome' },
      { icon: '🔗', ja: '腸-脳軸：迷走神経・免疫系・ホルモンで腸と脳は双方向通信', en: 'Gut-brain axis: bidirectional communication via vagus nerve, immune system, and hormones' },
      { icon: '😊', ja: 'セロトニン（幸福ホルモン）の90%は腸壁で産生される', en: '90% of serotonin (the happiness hormone) is produced in the gut wall' },
      { icon: '⚠️', ja: '腸管透過性亢進（リーキーガット）が全身炎症・自己免疫・うつの原因に', en: 'Increased intestinal permeability (leaky gut) drives systemic inflammation, autoimmunity & depression' },
    ],
    mechanismJa: `消化管は口→食道→胃→小腸（十二指腸・空腸・回腸）→大腸→直腸→肛門の一本の管。腸管神経系（ENS）は約5億個のニューロンを持ち脊髄と同等の複雑さで機能する。蠕動運動は自律神経と腸管ニューロンが協調して消化物を推し進める。腸内細菌はビタミンK・短鎖脂肪酸（SCFA）を産生し腸上皮の保護・免疫調節に必須。迷走神経は腸の状態（微生物信号含む）をリアルタイムで脳に伝達する。`,
    mechanismEn: `The gastrointestinal tract is a single tube from mouth → esophagus → stomach → small intestine (duodenum, jejunum, ileum) → large intestine → rectum → anus. The enteric nervous system (ENS) has ~500 million neurons — as complex as the spinal cord. Peristalsis is coordinated by autonomic nerves and enteric neurons. Gut bacteria produce vitamin K and short-chain fatty acids (SCFA) essential for intestinal protection and immune regulation. The vagus nerve transmits real-time gut status (including microbial signals) to the brain.`,
    yogaJa: `①蠕動促進：ねじりポーズ（マリーチャーサナ等）は腸管を物理的に圧迫・解放し蠕動を機械的に補助。②迷走神経-腸軸改善：深い腹式呼吸が迷走神経を活性化→消化機能向上→ガスや膨満感の解消。③コルチゾール低減：慢性ストレスはIBS（過敏性腸症候群）を悪化させる。ヨガのストレス低減がIBSを改善（Kuttner et al., 2006）。④腸内細菌多様性：Madan et al. (2020) でヨガ実践者の腸内フローラ多様性が高く有益菌（ラクトバチルス等）が増加。⑤腸管リンパ刺激：前屈ポーズで腸間膜リンパを活性化し免疫物質の循環を促進。`,
    yogaEn: `① Peristalsis: twisting poses (Marichyasana etc.) physically compress and release the gut, mechanically assisting peristalsis. ② Vagal-gut axis: deep abdominal breathing activates the vagus → improved digestion → gas and bloating relief. ③ Cortisol reduction: chronic stress worsens IBS. Yoga's stress reduction improves IBS (Kuttner et al., 2006). ④ Microbiome diversity: Madan et al. (2020) found yoga practitioners had greater gut microbiome diversity and increased beneficial bacteria (Lactobacillus etc.). ⑤ Mesenteric lymph: forward folds activate mesenteric lymph and circulate immune compounds.`,
    scienceJa: `Cryan & Dinan (2012, Nat Rev Neurosci)「腸-脳軸」レビュー：腸内細菌が精神健康に及ぼす多面的影響を体系化。Sonnenburg & Sonnenburg (2015)「The Good Gut」：食物繊維不足による腸内細菌多様性喪失が現代病の根源。`,
    scienceEn: `Cryan & Dinan (2012, Nat Rev Neurosci) "Gut-brain axis" review: systematized multifaceted gut microbiota effects on mental health. Sonnenburg & Sonnenburg (2015) "The Good Gut": loss of microbiome diversity from fiber deficiency as root of modern disease.`,
    poses: [
      { name: 'Seated Spinal Twist', effectJa: '腸管蠕動促進・肝臓・膵臓の刺激', effectEn: 'Peristalsis boost & liver/pancreas stimulation' },
      { name: 'Wind-Relieving Pose', effectJa: '大腸への直接圧迫でガス排出・蠕動促進', effectEn: 'Direct colon compression for gas relief & peristalsis' },
      { name: 'Bow Pose', effectJa: '腹腔内臓器の腹臥位マッサージ', effectEn: 'Prone massage of all abdominal organs' },
      { name: 'Abdominal Breathing', effectJa: '迷走神経-腸軸活性化・IBS改善', effectEn: 'Vagal-gut axis activation & IBS improvement' },
    ],
    bodyParts: ['🌿', '🧫', '🦠'],
    concernLinks: [
      {
        concernId: 'stress',
        reasonJa: '消化器系は脳に次ぐ約5億個のニューロンを持つ腸管神経系（ENS）を備え、迷走神経で脳と双方向通信する（腸-脳軸）。ストレスはENSを乱し過敏性腸症候群（IBS）・腸管透過性亢進（リーキーガット）を引き起こす。Fond et al. (2014, Eur Arch Psychiatry Clin Neurosci) でIBS患者の54%が不安・うつを合併することが示された。',
        reasonEn: 'The gut contains the enteric nervous system (ENS) with ~500 million neurons, communicating bidirectionally with the brain via the vagus nerve (gut-brain axis). Stress disrupts the ENS, causing IBS and increased intestinal permeability (leaky gut). Fond et al. (2014) showed 54% of IBS patients have comorbid anxiety/depression.',
        yogaJa: 'Kuttner et al. (2006, J Pediatr Gastroenterol Nutr) のRCTでヨガがIBS症状（腹痛・下痢・不安）を有意に改善した。ヨガによる副交感神経優位化が迷走神経を通じて「休息と消化」モードを回復させ、腸管蠕動の正常化と腸内細菌叢の多様性維持に貢献する。',
        yogaEn: 'Kuttner et al. (2006, J Pediatr Gastroenterol Nutr) RCT showed yoga significantly improved IBS symptoms (abdominal pain, diarrhea, anxiety). Yoga-induced parasympathetic dominance restores "rest and digest" mode via the vagus nerve, normalizing gut motility and maintaining microbiome diversity.',
        evidence: 'Kuttner et al. (2006, J Pediatr Gastroenterol Nutr)',
      },
      {
        concernId: 'recovery',
        reasonJa: '消化・吸収効率は疲労回復の栄養面での基盤。ストレス下では腸管蠕動が遅延し、栄養素の吸収率が低下する。さらにリーキーガットは炎症を全身に広げ回復を妨げる。腸内細菌が産生する短鎖脂肪酸（SCFA）が腸管免疫と全身の炎症コントロールに必須。',
        reasonEn: 'Digestive and absorption efficiency is the nutritional foundation of recovery. Under stress, gut motility slows and nutrient absorption decreases. Leaky gut spreads inflammation systemically, impeding recovery. Short-chain fatty acids (SCFA) produced by gut bacteria are essential for gut immunity and systemic inflammation control.',
        yogaJa: 'ねじりポーズ（マリーチャーサナ・スプタマツィエンドラーサナ）は腹腔内臓器を物理的に圧迫・解放し蠕動を促進する。風邪抜きポーズ（パヴァナムクターサナ）は大腸への直接マッサージとなりガス排出と消化を助ける。副交感神経優位化が消化酵素分泌を回復させ栄養吸収を最大化する。',
        yogaEn: 'Twisting poses (Marichyasana, Supta Matsyendrasana) physically compress and release abdominal organs, promoting peristalsis. Wind-Relieving Pose directly massages the colon, aiding gas expulsion and digestion. Parasympathetic activation restores digestive enzyme secretion, maximizing nutrient absorption.',
        evidence: 'Kuttner et al. (2006); Madan et al. (2020) — yoga practitioners show greater gut microbiome diversity',
      },
      {
        concernId: 'sleep',
        reasonJa: '腸内細菌は脳内セロトニンの約90%を産生する。セロトニンは松果体でメラトニンの前駆体として使われるため、腸内フローラの健全性が睡眠ホルモン産生を直接制御する。Thaiss et al. (2014, Cell) で腸内細菌が24時間概日リズムを持つことが示された。',
        reasonEn: 'Gut bacteria produce ~90% of the brain\'s serotonin. Since serotonin is used as a melatonin precursor in the pineal gland, gut microbiome health directly controls sleep hormone production. Thaiss et al. (2014, Cell) showed gut bacteria exhibit 24-hour circadian rhythms.',
        yogaJa: 'ヨガのストレス低減が腸内フローラ多様性を維持し（Madan et al., 2020）、セロトニン産生を安定させてメラトニンリズムを正常化する。就寝前の腹式呼吸・ねじりで腸の副交感神経刺激を行うことが消化器系-睡眠サイクルを整える実践的アプローチ。',
        yogaEn: 'Yoga\'s stress reduction maintains gut microbiome diversity (Madan et al., 2020), stabilizing serotonin production and normalizing the melatonin rhythm. Pre-sleep abdominal breathing and twists stimulate gut parasympathetic activity, a practical approach to aligning the digestive-sleep cycle.',
        evidence: 'Thaiss et al. (2014, Cell); Madan et al. (2020)',
      },
    ],
  },

  {
    id: 'urinary',
    icon: '💧',
    nameJa: '泌尿器系',
    nameEn: 'Urinary System',
    taglineJa: '腎臓は1日180Lの血液をろ過し体内環境を精密に維持する',
    taglineEn: 'Kidneys filter 180L of blood daily, maintaining the body\'s precise internal environment',
    color: 'blue',
    bg: 'bg-blue-50 dark:bg-blue-950/30',
    border: 'border-blue-200 dark:border-blue-800',
    text: 'text-blue-700 dark:text-blue-300',
    badge: 'bg-blue-100 dark:bg-blue-900/50 text-blue-700 dark:text-blue-300',
    summaryJa: '腎臓は血圧・電解質・pH・赤血球産生を統合制御する。ヨガの深呼吸と腎臓への血流改善は腎機能を保護する。',
    summaryEn: 'Kidneys integrate blood pressure, electrolytes, pH, and red blood cell production. Yoga\'s deep breathing and improved renal blood flow protect kidney function.',
    facts: [
      { icon: '🔬', ja: 'ネフロン（腎の機能単位）は1つの腎臓に約100万個', en: '~1 million nephrons (functional units) per kidney' },
      { icon: '🩸', ja: '腎臓はレニンを分泌し血圧をRAA系で精密制御', en: 'Kidneys secrete renin, controlling blood pressure via the RAA system' },
      { icon: '🌡️', ja: '酸塩基平衡（pH7.35〜7.45）の維持は腎臓が主担当', en: 'Kidneys are primary responsible for acid-base balance (pH 7.35–7.45)' },
      { icon: '🫁', ja: 'エリスロポエチン（EPO）で赤血球産生を制御', en: 'Erythropoietin (EPO) produced by kidneys controls red blood cell production' },
    ],
    mechanismJa: `腎臓はネフロン（糸球体＋尿細管）で血液をろ過、必要物質を再吸収し不要物質を尿として排出。1日約180Lをろ過し1.5Lの尿を産生。RAAS（レニン-アンジオテンシン-アルドステロン系）で血圧・Na/K・体液量を精密調節。伝統中医学の腎経は腸腰筋・内転筋・足裏のアーチに沿い、ヨガの股関節・内腿ポーズが「腎経」を流れると言われる（現代解剖学との統合視点）。`,
    mechanismEn: `Kidneys filter blood through nephrons (glomerulus + tubules), reabsorbing needed substances and excreting waste as urine. They filter ~180L/day to produce 1.5L of urine. The RAAS (renin-angiotensin-aldosterone system) precisely regulates blood pressure, Na/K balance, and fluid volume. Traditional Chinese Medicine's kidney meridian runs along the psoas, adductors, and plantar arch — hip and inner thigh yoga poses are said to "stimulate the kidney meridian" (integrated with modern anatomy).`,
    yogaJa: `①腎臓への血流増加：有酸素的ヴィンヤサ後に腎血流量が増加し糸球体ろ過率が向上。②ストレス低減：慢性ストレス→レニン分泌亢進→高血圧→腎障害の連鎖をヨガが断ち切る。③ヒップオープナー（鳩のポーズ・花輪のポーズ）：腸腰筋リリースが腎臓周辺の血流・リンパ流を改善（陰ヨガの腎経アプローチと一致）。④深呼吸：横隔膜の下降が腎臓を物理的にマッサージし（腎臓は横隔膜直下）血流を促進。⑤水分補給意識：ヨガ実践が水分摂取習慣を高め腎機能を保護。`,
    yogaEn: `① Increased renal blood flow: aerobic vinyasa improves renal blood flow and glomerular filtration rate. ② Stress reduction: chronic stress → renin secretion → hypertension → renal damage — yoga interrupts this chain. ③ Hip openers (Pigeon, Garland): psoas release improves blood flow and lymph around the kidneys (aligned with yin yoga's kidney meridian approach). ④ Deep breathing: diaphragm descent physically massages the kidneys (located directly below the diaphragm) and stimulates blood flow. ⑤ Hydration awareness: yoga practice raises awareness of hydration habits, protecting renal function.`,
    scienceJa: `Cramer et al. (2014)：ヨガが高血圧を改善しCKD（慢性腎臓病）進行リスクを低減。伝統中医学の腎経と筋膜経線（Myers「Anatomy Trains」深前線）の解剖学的対応が研究されている。`,
    scienceEn: `Cramer et al. (2014): yoga improves hypertension and reduces CKD (chronic kidney disease) progression risk. Anatomical correspondence between TCM kidney meridian and the Deep Front Line (Myers "Anatomy Trains") is under active research.`,
    poses: [
      { name: 'Pigeon Pose', effectJa: '腸腰筋リリース・腎周囲血流改善（腎経）', effectEn: 'Psoas release & perirenale blood flow (kidney meridian)' },
      { name: 'Garland Pose', effectJa: '骨盤底筋・腎臓周辺リンパ活性化', effectEn: 'Pelvic floor & perirenal lymphatic activation' },
      { name: 'Reclined Hero', effectJa: '腸腰筋ストレッチ・腎臓への圧迫軽減', effectEn: 'Psoas stretch & decompression of kidneys' },
      { name: 'Pranayama', effectJa: '横隔膜による腎臓マッサージ・腎血流促進', effectEn: 'Diaphragmatic massage of kidneys & improved renal flow' },
    ],
    bodyParts: ['💧', '🔬', '🩸'],
    concernLinks: [
      {
        concernId: 'stress',
        reasonJa: '慢性ストレス→レニン分泌亢進→アンジオテンシンII→血管収縮→高血圧→腎小球への過剰圧力のカスケードが腎障害の主経路。慢性腎臓病（CKD）患者の第一リスク因子が高血圧であり、その根本にストレス性自律神経失調がある。',
        reasonEn: 'Chronic stress → elevated renin → angiotensin II → vasoconstriction → hypertension → excess glomerular pressure is the primary pathway to kidney damage. Hypertension is the #1 risk factor for CKD, rooted in stress-induced autonomic dysfunction.',
        yogaJa: 'ヨガによる降圧効果（Cramer et al., 2014: SBP −4.2 mmHg）が腎小球ろ過圧を正常化し腎保護に働く。リストラティブヨガは副腎からのアルドステロン分泌を低下させ、RAA系（レニン-アンジオテンシン-アルドステロン）全体を鎮静させる。',
        yogaEn: 'Yoga\'s antihypertensive effect (Cramer et al., 2014: SBP −4.2 mmHg) normalizes glomerular filtration pressure, protecting the kidneys. Restorative yoga reduces aldosterone secretion from the adrenals, calming the entire RAAS.',
        evidence: 'Cramer et al. (2014, J Hypertens); Gordon et al. (2008) — yoga and renal function in hypertension',
      },
      {
        concernId: 'recovery',
        reasonJa: '腎臓は1日約180Lの血液をろ過し尿素・クレアチニン・乳酸などの代謝老廃物を排出する。運動後の代謝廃棄物処理速度が腎血流量に依存するため、腎機能の健全性が身体回復の重要な決定因子。',
        reasonEn: 'Kidneys filter ~180L of blood daily, excreting metabolic waste (urea, creatinine, lactate). The speed of post-exercise metabolic waste clearance depends on renal blood flow, making kidney health a critical determinant of physical recovery.',
        yogaJa: 'ヒップオープナー（鳩のポーズ・花輪のポーズ）は腸腰筋のリリースを通じ腎周囲の血流・リンパ流を改善する。深呼吸による横隔膜の大幅な収縮は腎臓（横隔膜直下に位置）を物理的にマッサージし、腎血流を促進して老廃物除去を加速する。',
        yogaEn: 'Hip openers (Pigeon, Garland) improve perirenale blood flow and lymph via psoas release. Large diaphragmatic contractions in deep breathing physically massage the kidneys (located directly below the diaphragm), promoting renal blood flow and accelerating waste removal.',
        evidence: 'Anatomically grounded mechanism; Cramer et al. (2014, J Hypertens)',
      },
    ],
  },

  {
    id: 'reproductive',
    icon: '🌸',
    nameJa: '生殖・骨盤底系',
    nameEn: 'Reproductive & Pelvic Floor System',
    taglineJa: '骨盤底は全ての内臓を支えるハンモック—呼吸と連動する',
    taglineEn: 'The pelvic floor is a hammock supporting all organs — it moves with every breath',
    color: 'fuchsia',
    bg: 'bg-fuchsia-50 dark:bg-fuchsia-950/30',
    border: 'border-fuchsia-200 dark:border-fuchsia-800',
    text: 'text-fuchsia-700 dark:text-fuchsia-300',
    badge: 'bg-fuchsia-100 dark:bg-fuchsia-900/50 text-fuchsia-700 dark:text-fuchsia-300',
    summaryJa: 'ムーラ・バンダ（会陰の収縮）は骨盤底を鍛えるケーゲル運動と同等。ヨガの深呼吸は骨盤底を毎回受動的にトレーニングする。',
    summaryEn: 'Mula Bandha (perineal lock) equals Kegel exercises for pelvic floor. Every deep yoga breath passively trains the pelvic floor.',
    facts: [
      { icon: '🪢', ja: 'ムーラ・バンダ（会陰収縮）は骨盤底全層を活性化するヨガの技法', en: 'Mula Bandha (perineal contraction) activates all pelvic floor layers' },
      { icon: '🔄', ja: '骨盤底は吸気で下降（弛緩）、呼気で上昇（収縮）する呼吸連動運動をする', en: 'Pelvic floor descends on inhalation and rises on exhalation — breathing IS pelvic floor training' },
      { icon: '💊', ja: 'コルチゾール過剰は生殖ホルモン（エストロゲン・テストステロン）を抑制する', en: 'Excess cortisol suppresses reproductive hormones (estrogen & testosterone)' },
      { icon: '🌙', ja: '月経周期の各相でホルモンが変動しヨガの選択が変わる', en: 'Hormones fluctuate across menstrual phases — optimal yoga practice varies by phase' },
    ],
    mechanismJa: `骨盤底は尾骨から恥骨まで広がる複数層の筋群（肛門挙筋・尾骨筋等）で構成され、膀胱・子宮・直腸を下から支える。吸気で横隔膜が下降すると骨盤底も反射的に下降（弛緩）し、呼気で上昇（収縮）する—横隔膜と骨盤底は「ピストンシステム」として協調する。生殖系では視床下部-下垂体-性腺軸（HPG軸）がGnRH→FSH/LH→性ホルモンを段階的に調節。慢性ストレスはHPA軸がHPG軸を抑制することで性欲低下・月経不順・不妊に至る。`,
    mechanismEn: `The pelvic floor is a multi-layer muscle group (levator ani, coccygeus, etc.) spanning from coccyx to pubis, supporting the bladder, uterus, and rectum from below. On inhalation, the diaphragm descends and the pelvic floor reflexively descends (relaxes); on exhalation, both rise (contract) — the diaphragm and pelvic floor function as a "piston system." The HPG axis (hypothalamus → pituitary → gonads) regulates GnRH → FSH/LH → sex hormones. Chronic stress via HPA axis suppression of the HPG axis leads to reduced libido, menstrual irregularity, and infertility.`,
    yogaJa: `①ムーラ・バンダ：会陰の意識的収縮でI型・II型骨盤底筋繊維を鍛える。尿失禁・骨盤臓器脱の予防・改善に有効。②呼吸によるパッシブトレーニング：深い腹式呼吸が吸気・呼気ごとに骨盤底を自動的にトレーニング。③ヒップオープナー（鳩・花輪・蜥蜴）：骨盤内の血流・リンパ流を増加させ生殖器への栄養供給を改善。④月経相別アプローチ：月経期（リストラティブ中心）→卵胞期（エネルギー系）→排卵期（バランス）→黄体期（陰ヨガ中心）。⑤コルチゾール低減：HPG軸の回復で性ホルモンバランスが改善、月経不順・PMS・更年期症状を軽減（Nidich et al., 2009）。`,
    yogaEn: `① Mula Bandha: conscious perineal contraction trains Type I & II pelvic floor muscle fibers. Effective for urinary incontinence prevention and pelvic organ prolapse. ② Passive training via breathing: deep abdominal breathing automatically trains the pelvic floor with each inhalation and exhalation. ③ Hip openers (Pigeon, Garland, Lizard): increase pelvic blood flow and lymph, improving nutrient delivery to reproductive organs. ④ Menstrual phase approach: menstrual phase (restorative) → follicular (energetic) → ovulation (balance) → luteal (yin-focused). ⑤ Cortisol reduction: HPG axis recovery improves sex hormone balance, reducing menstrual irregularity, PMS, and menopausal symptoms (Nidich et al., 2009).`,
    scienceJa: `Nidich et al. (2009)：TM瞑想が更年期症状（ホットフラッシュ）を有意に改善。Brotto & Basson (2014)：マインドフルネスが女性性機能障害に有効。骨盤底と横隔膜の協調（Hodges et al., 2007）：正常呼吸が骨盤底を受動的にトレーニングする初の実証。`,
    scienceEn: `Nidich et al. (2009): TM meditation significantly improves menopausal symptoms (hot flashes). Brotto & Basson (2014): mindfulness is effective for female sexual dysfunction. Hodges et al. (2007): first empirical demonstration that normal breathing passively trains the pelvic floor.`,
    poses: [
      { name: 'Garland Pose', effectJa: '骨盤底全層活性化・ムーラ・バンダ練習', effectEn: 'Full pelvic floor activation & Mula Bandha practice' },
      { name: 'Pigeon Pose', effectJa: '腸腰筋・梨状筋解放・骨盤内血流促進', effectEn: 'Psoas/piriformis release & pelvic circulation boost' },
      { name: 'Reclined Bound Angle', effectJa: '骨盤内臓器への血流最大化・緊張解放', effectEn: 'Maximum blood flow to pelvic organs & tension release' },
      { name: 'Bridge Pose', effectJa: '骨盤底・臀筋・ハムストリングスの統合強化', effectEn: 'Integrated pelvic floor, glute & hamstring strengthening' },
    ],
    bodyParts: ['🌸', '🪢', '💐'],
    concernLinks: [
      {
        concernId: 'stress',
        reasonJa: 'HPA軸（コルチゾール）とHPG軸（性ホルモン）は視床下部レベルで拮抗する。慢性ストレス→GnRH（性腺刺激ホルモン放出ホルモン）抑制→LH/FSH低下→エストロゲン/テストステロン低下→月経不順・性欲低下・不妊が生じる（Rivier & Rivest, 1991, Endocrinology）。',
        reasonEn: 'The HPA axis (cortisol) and HPG axis (sex hormones) antagonize each other at the hypothalamic level. Chronic stress → GnRH suppression → LH/FSH reduction → estrogen/testosterone decline → menstrual irregularity, reduced libido, and infertility (Rivier & Rivest, 1991, Endocrinology).',
        yogaJa: 'Nidich et al. (2009, Menopause) のRCTでTM（超越瞑想）が更年期のホットフラッシュを有意に改善した。ヨガによるコルチゾール低減はHPG軸の回復を通じてホルモンバランスを正常化し、PMS・月経不順・更年期症状を軽減する。',
        yogaEn: 'Nidich et al. (2009, Menopause) RCT demonstrated TM (transcendental meditation) significantly improved menopausal hot flashes. Yoga\'s cortisol reduction normalizes hormone balance via HPG axis recovery, alleviating PMS, menstrual irregularity, and menopausal symptoms.',
        evidence: 'Nidich et al. (2009, Menopause); Rivier & Rivest (1991, Endocrinology)',
      },
      {
        concernId: 'posture',
        reasonJa: '前傾骨盤（腸腰筋短縮）は腰椎前弯を過剰にし骨盤底の張力バランスを乱す。骨盤底の非対称な緊張は骨盤内臓器の支持を低下させ、尿失禁・骨盤痛・腰痛の原因となる（Lee & Hodges, 2016, J Anat）。',
        reasonEn: 'Anterior pelvic tilt (shortened iliopsoas) excessively increases lumbar lordosis and disrupts pelvic floor tension balance. Asymmetric pelvic floor tension reduces pelvic organ support, causing urinary incontinence, pelvic pain, and low back pain (Lee & Hodges, 2016, J Anat).',
        yogaJa: 'ウォーリアーシリーズと鳩のポーズで腸腰筋を伸ばしながら臀筋を強化し、骨盤中立位を回復させる。山のポーズでの正確な骨盤アライメントと腹部軽度緊張の組み合わせが骨盤底-脊柱-肩帯の統合的な姿勢改善を実現する。',
        yogaEn: 'Warrior series and Pigeon Pose stretch the iliopsoas while strengthening the glutes, restoring neutral pelvic alignment. Tadasana with precise pelvic alignment and mild abdominal engagement achieves integrated postural improvement of the pelvic floor-spine-shoulder girdle.',
        evidence: 'Lee & Hodges (2016, Journal of Anatomy)',
      },
      {
        concernId: 'core',
        reasonJa: '骨盤底は深部体幹「圧力シリンダー」の底面を構成し、横隔膜と協調して腹腔内圧を制御する。Hodges et al. (2007, J Appl Physiol) は正常呼吸サイクルで骨盤底が横隔膜と同期して収縮・弛緩することを実証し、呼吸=骨盤底トレーニングであることを示した。',
        reasonEn: 'The pelvic floor forms the base of the deep core "pressure cylinder," coordinating with the diaphragm to control intra-abdominal pressure. Hodges et al. (2007, J Appl Physiol) demonstrated that the pelvic floor contracts and relaxes synchronously with the diaphragm during normal breathing — breathing IS pelvic floor training.',
        yogaJa: 'ムーラ・バンダ（会陰の意識的収縮）はケーゲル運動と同等の骨盤底I型・II型筋線維トレーニング。深い腹式呼吸の毎回が骨盤底をパッシブにトレーニングする。花輪のポーズは骨盤底全層を活性化し、尿失禁・骨盤臓器脱の予防に直接効果がある。',
        yogaEn: 'Mula Bandha (conscious perineal contraction) provides equivalent Type I and II pelvic floor fiber training to Kegel exercises. Every deep abdominal breath passively trains the pelvic floor. Garland Pose activates all pelvic floor layers and has direct preventive effects on urinary incontinence and pelvic organ prolapse.',
        evidence: 'Hodges et al. (2007, Journal of Applied Physiology)',
      },
    ],
  },
]
