import { createClient } from '@/lib/supabase/server'
import { NextRequest, NextResponse } from 'next/server'
import type { EmailOtpType } from '@supabase/supabase-js'

export async function GET(request: NextRequest) {
  const { searchParams, origin } = new URL(request.url)

  // ── Parameters ──────────────────────────────────────────────────────────────
  // PKCE flow (Google OAuth, normal email sign-in)
  const code = searchParams.get('code')
  // Token-hash flow (Admin API generateLink — used for our password reset)
  const token_hash = searchParams.get('token_hash')
  const type = searchParams.get('type') // 'recovery' | 'signup' | 'magiclink' …

  const role = searchParams.get('role') || 'student'

  // Cookie set by /api/auth/send-reset when the reset email is dispatched
  const isRecovery =
    request.cookies.get('ry_recovery')?.value === '1' || type === 'recovery'

  const supabase = await createClient()

  // ── Helper: clear recovery cookie and redirect ───────────────────────────
  function recoveryRedirect() {
    const res = NextResponse.redirect(`${origin}/auth/reset-password`)
    res.cookies.set('ry_recovery', '', { path: '/', maxAge: 0 })
    return res
  }

  // ── Helper: redirect to dashboard based on role ──────────────────────────
  async function dashboardRedirect() {
    const {
      data: { user },
    } = await supabase.auth.getUser()
    if (!user) return NextResponse.redirect(`${origin}/login?error=auth_failed`)

    const { data: profile } = await supabase
      .from('profiles')
      .select('role')
      .eq('id', user.id)
      .single()

    if (!profile?.role || profile.role === 'student') {
      return NextResponse.redirect(`${origin}/onboarding?role=${role}`)
    }
    if (profile.role === 'instructor') {
      return NextResponse.redirect(`${origin}/instructor/dashboard`)
    }
    if (profile.role === 'admin') {
      return NextResponse.redirect(`${origin}/admin/dashboard`)
    }
    return NextResponse.redirect(`${origin}/dashboard`)
  }

  // ── Token-hash flow (Admin API / Magic Link / Email OTP) ─────────────────
  // This is the path taken when the password reset email generated by
  // supabase.auth.admin.generateLink() is clicked.
  if (token_hash && type) {
    const { error } = await supabase.auth.verifyOtp({
      token_hash,
      type: type as EmailOtpType,
    })

    if (!error) {
      if (isRecovery) return recoveryRedirect()
      return dashboardRedirect()
    }

    console.error('[callback] verifyOtp error:', error.message)
    return NextResponse.redirect(`${origin}/login?error=link_expired`)
  }

  // ── PKCE code flow (Google OAuth, standard email confirmation) ────────────
  if (code) {
    const { error } = await supabase.auth.exchangeCodeForSession(code)

    if (!error) {
      if (isRecovery) return recoveryRedirect()
      return dashboardRedirect()
    }

    console.error('[callback] exchangeCodeForSession error:', error.message)
    return NextResponse.redirect(`${origin}/login?error=link_expired`)
  }

  return NextResponse.redirect(`${origin}/login?error=auth_failed`)
}
